package com.samanramezani1377.woogit.core.domain.repository

import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*

interface OrderRepository { suspend fun get(storeId:StoreId,id:EntityId):CoreResult<Order>; suspend fun list(storeId:StoreId,page:Int=1,perPage:Int=20,search:String?=null,status:String?=null):CoreResult<List<Order>>; suspend fun update(storeId:StoreId,id:EntityId,order:Order):CoreResult<Order> }
interface OrderNoteRepository { suspend fun addNote(storeId:StoreId,orderId:EntityId,content:String,customerNote:Boolean=false):CoreResult<OrderNote> }
interface ProductRepository { suspend fun get(storeId:StoreId,id:EntityId):CoreResult<Product>; suspend fun list(storeId:StoreId,page:Int=1,perPage:Int=20,search:String?=null):CoreResult<List<Product>>; suspend fun create(storeId:StoreId,product:Product):CoreResult<Product>; suspend fun update(storeId:StoreId,id:EntityId,product:Product):CoreResult<Product>; suspend fun delete(storeId:StoreId,id:EntityId):CoreResult<Unit> }
interface VariationRepository { suspend fun list(storeId:StoreId,productId:EntityId,page:Int=1,perPage:Int=20):CoreResult<List<Variation>>; suspend fun get(storeId:StoreId,productId:EntityId,id:EntityId):CoreResult<Variation>; suspend fun create(storeId:StoreId,value:Variation):CoreResult<Variation>; suspend fun update(storeId:StoreId,productId:EntityId,id:EntityId,value:Variation):CoreResult<Variation>; suspend fun delete(storeId:StoreId,productId:EntityId,id:EntityId):CoreResult<Unit> }
interface AttributeRepository { suspend fun list(storeId:StoreId,page:Int=1,perPage:Int=100):CoreResult<List<GlobalAttribute>>; suspend fun get(storeId:StoreId,id:EntityId):CoreResult<GlobalAttribute>; suspend fun create(storeId:StoreId,value:GlobalAttribute):CoreResult<GlobalAttribute>; suspend fun update(storeId:StoreId,id:EntityId,value:GlobalAttribute):CoreResult<GlobalAttribute>; suspend fun delete(storeId:StoreId,id:EntityId):CoreResult<Unit> }
interface TermRepository { suspend fun list(storeId:StoreId,attributeId:EntityId,page:Int=1,perPage:Int=100):CoreResult<List<AttributeTerm>>; suspend fun get(storeId:StoreId,attributeId:EntityId,id:EntityId):CoreResult<AttributeTerm>; suspend fun create(storeId:StoreId,attributeId:EntityId,value:AttributeTerm):CoreResult<AttributeTerm>; suspend fun update(storeId:StoreId,attributeId:EntityId,id:EntityId,value:AttributeTerm):CoreResult<AttributeTerm>; suspend fun delete(storeId:StoreId,attributeId:EntityId,id:EntityId):CoreResult<Unit> }
interface StoreRepository { suspend fun get(id:StoreId):CoreResult<StoreConnection>; suspend fun save(store:StoreConnection):CoreResult<StoreConnection>; suspend fun connect(store:StoreConnection,consumerKey:String,consumerSecret:String):CoreResult<StoreConnection>; suspend fun disconnect(id:StoreId):CoreResult<Unit> }
interface PendingOperationRepository { suspend fun getPending(storeId:StoreId):CoreResult<List<PendingOperation>>; suspend fun enqueue(operation:PendingOperation):CoreResult<Unit>; suspend fun claim(operationId:EntityId):CoreResult<Boolean>; suspend fun markSucceeded(operationId:EntityId):CoreResult<Unit>; suspend fun markRetry(operationId:EntityId,retryCount:Int,nextAttemptAt:Long,error:String):CoreResult<Unit>; suspend fun markFailed(operationId:EntityId,error:String):CoreResult<Unit> }
interface SyncRepository { suspend fun sync(storeId:StoreId):CoreResult<Unit>; suspend fun getState(storeId:StoreId):CoreResult<SyncMetadata>; suspend fun getConflicts(storeId:StoreId):CoreResult<List<Conflict>>; suspend fun resolveConflict(storeId:StoreId,conflictId:EntityId,resolution:ConflictResolution):CoreResult<Unit> }
