package com.samanramezani1377.woogit.presentation.settings

import android.content.ContentResolver
import android.net.Uri
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.presentation.V1PresentationDependencies
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import java.io.ByteArrayOutputStream
import java.util.Locale
import java.util.zip.ZipInputStream

private val createNewJson = Json { ignoreUnknownKeys = true; explicitNulls = false }
private const val CREATE_NEW_FORMAT = "woogit-products"
private const val CREATE_NEW_VERSION = 2
private const val CREATE_NEW_MAX_PRODUCTS = 10_000
private const val CREATE_NEW_MAX_ENTRY_BYTES = 50L * 1024L * 1024L
private const val CREATE_NEW_MAX_PACKAGE_BYTES = 1_073_741_824L
private const val NEW_ID = "new"

@Serializable private data class CreatePackage(val manifest:CreateManifest,val products:List<CreateProduct>,val globalAttributes:List<CreateGlobalAttribute> = emptyList())
@Serializable private data class CreateManifest(val format:String=CREATE_NEW_FORMAT,val version:Int=1,val source:String="",val exportedAt:String="",val products:Int=0,val images:Int=0)
@Serializable private data class CreateProduct(val id:String,val name:String,val sku:String?=null,val description:String?=null,val shortDescription:String?=null,val status:String,val type:String,val regular:String?=null,val sale:String?=null,val onSale:Boolean,val quantity:Double?=null,val stockStatus:String?=null,val manageStock:Boolean,val categories:List<CreateIdName> = emptyList(),val attributes:List<CreateAttribute> = emptyList(),val images:List<CreateImage> = emptyList(),val variations:List<CreateVariation> = emptyList())
@Serializable private data class CreateVariation(val id:String,val sku:String?=null,val regular:String?=null,val sale:String?=null,val onSale:Boolean,val quantity:Double?=null,val stockStatus:String?=null,val manageStock:Boolean,val attributes:List<CreateVariationAttribute> = emptyList(),val image:CreateImage?=null)
@Serializable private data class CreateVariationAttribute(val name:String,val option:String)
@Serializable private data class CreateIdName(val id:String,val name:String,val parentId:String?=null)
@Serializable private data class CreateAttribute(val id:String?=null,val name:String,val visible:Boolean,val variation:Boolean,val options:List<String>)
@Serializable private data class CreateImage(val id:String?=null,val src:String,val name:String?=null,val alt:String?=null,val file:String)
@Serializable private data class CreateGlobalAttribute(val id:String,val name:String,val slug:String,val terms:List<CreateTerm> = emptyList())
@Serializable private data class CreateTerm(val id:String?=null,val name:String,val slug:String?=null)
private data class CreateReadPackage(val manifest:CreateManifest,val products:List<CreateProduct>,val media:Map<String,ByteArray>,val globals:List<CreateGlobalAttribute>)

class CreateNewProductTransferService(private val d:V1PresentationDependencies,private val resolver:ContentResolver){
 suspend fun import(storeId:StoreId,source:Uri,createAsDraft:Boolean=false,onProgress:(ProductTransferProgress)->Unit={}):RobustProductTransferResult=withContext(Dispatchers.IO){try{
  val pack=readPackage(source);require(pack.manifest.format==CREATE_NEW_FORMAT);require(pack.manifest.version<=CREATE_NEW_VERSION);require(pack.products.size<=CREATE_NEW_MAX_PRODUCTS);val existing=allProducts(storeId);val used=existing.mapNotNullTo(mutableSetOf()){normalizeSku(it.sku)};existing.filter{it.type==ProductType.VARIABLE}.forEach{allVars(storeId,it.id).forEach{v->normalizeSku(v.sku)?.let(used::add)}}
  val categories=allCategories(storeId).toMutableList();val byId=categories.associateBy{it.id.value}.toMutableMap();val byPath=categories.associateBy{categoryPath(it,byId)}.toMutableMap();val uploaded=linkedMapOf<String,ProductImage>();var created=0;var failed=0;var imagesUploaded=0;var variationsCreated=0;var variationsFailed=0;var skuChanged=0;var categoriesCreated=0;var categoriesResolved=0;var attributesCreated=0;var attributesResolved=0;var termsCreated=0;var termsResolved=0;val errors=mutableListOf<String>()
  for(file in pack.media){when(val r=d.uploadMedia(storeId,file.key.substringAfterLast('/'),file.value,mime(file.key))){is CoreResult.Success->{uploaded[file.key]=r.value;imagesUploaded++};is CoreResult.Failure->errors+="تصویر ${file.key} وارد نشد: ${r.error}"}}
  val attrMap=mutableMapOf<String,EntityId>();for(g in pack.globals){val existingAttr=when(val r=d.getAttributes(storeId,1,100)){is CoreResult.Success->r.value.firstOrNull{normalize(it.slug)==normalize(g.slug)||normalize(it.name)==normalize(g.name)};is CoreResult.Failure->null};val dest=if(existingAttr!=null){attributesResolved++;existingAttr}else when(val r=d.createAttribute(storeId,GlobalAttribute(EntityId(NEW_ID),g.name,g.slug,emptyList()))){is CoreResult.Success->{attributesCreated++;r.value};is CoreResult.Failure->{errors+="ویژگی سراسری «${g.name}» ساخته نشد: ${r.error}";continue}};attrMap[g.id]=dest.id;val terms=when(val r=d.getTerms(storeId,dest.id,1,100)){is CoreResult.Success->r.value;is CoreResult.Failure->emptyList()};for(t in g.terms){if(terms.any{normalize(it.name)==normalize(t.name)||normalize(it.slug)==normalize(t.slug)}){termsResolved++}else when(val r=d.createTerm(storeId,dest.id,AttributeTerm(EntityId(NEW_ID),t.name,t.slug))){is CoreResult.Success->termsCreated++;is CoreResult.Failure->errors+="Term «${t.name}» ساخته نشد: ${r.error}"}}}
  for((index,x) in pack.products.withIndex()){onProgress(ProductTransferProgress("در حال ایجاد محصولات جدید…",index+1,pack.products.size));try{val images=x.images.mapNotNull{uploaded[it.file]};val resolved=resolveCategories(storeId,x.categories,byId,byPath,errors){categoriesCreated++;categoriesResolved};val attrs=x.attributes.map{Attribute(it.id?.let(attrMap::get),it.name,it.visible,it.variation,it.options)};val sku=nextUniqueSku(x.sku,used).also{if(it!=null&&!it.equals(x.sku,false))skuChanged++};sku?.let{used+=normalizeSku(it)};val product=x.toDomain(EntityId(NEW_ID),images,resolved,attrs,sku).let{if(createAsDraft)it.copy(status=ProductStatus.DRAFT)else it};when(val r=d.createProduct(storeId,product)){is CoreResult.Success->{created++;for(v in x.variations){val vs=nextUniqueSku(v.sku,used);vs?.let{used+=normalizeSku(it)};val image=v.image?.let{uploaded[it.file]};when(val vr=d.createVariation(storeId,v.toDomain(r.value.id,image,vs))){is CoreResult.Success->variationsCreated++;is CoreResult.Failure->{variationsFailed++;errors+="${x.name}: variation ${v.sku?:v.id} ایجاد نشد: ${vr.error}"}}}};is CoreResult.Failure->{failed++;errors+="${x.name}: ${r.error}"}}}catch(t:Throwable){failed++;errors+="${x.name}: ${t.message?:"خطای نامشخص"}"}}
  RobustProductTransferResult(created=created,failed=failed,imagesUploaded=imagesUploaded,variationsCreated=variationsCreated,variationsFailed=variationsFailed,skuChanged=skuChanged,errors=errors.distinct().take(50),categoriesCreated=categoriesCreated,categoriesResolved=categoriesResolved,attributesCreated=attributesCreated,attributesResolved=attributesResolved,termsCreated=termsCreated,termsResolved=termsResolved)
 }catch(t:Throwable){RobustProductTransferResult(failed=1,errors=listOf(t.message?:"خواندن فایل ناموفق بود."))}}
 private fun normalizeSku(v:String?):String?=v?.trim()?.takeIf{it.isNotEmpty()}?.lowercase(Locale.ROOT)
 private fun nextUniqueSku(original:String?,used:Set<String>):String?{val base=original?.trim()?.takeIf{it.isNotEmpty()}?:return null;var c=base;while(normalizeSku(c) in used)c="0$c";return c}
 private fun readPackage(uri:Uri):CreateReadPackage{var manifest:CreateManifest?=null;var products:List<CreateProduct>?=null;var globals=emptyList<CreateGlobalAttribute>();val media=linkedMapOf<String,ByteArray>();var total=0L;resolver.openInputStream(uri)?.use{input->ZipInputStream(input).use{zip->while(true){val e=zip.nextEntry?:break;if(e.isDirectory)continue;require(!e.name.contains("..")&&!e.name.startsWith('/'));val bytes=readLimited(zip,if(e.name=="products.json")100L*1024*1024 else CREATE_NEW_MAX_ENTRY_BYTES){total+=it;require(total<=CREATE_NEW_MAX_PACKAGE_BYTES)};when(e.name){"manifest.json"->manifest=createNewJson.decodeFromString(bytes.toString(Charsets.UTF_8));"products.json"->{val p=createNewJson.decodeFromString<CreatePackage>(bytes.toString(Charsets.UTF_8));manifest=manifest?:p.manifest;products=p.products;globals=p.globalAttributes};else->if(e.name.startsWith("media/"))media[e.name]=bytes}}}}?:error("فایل قابل خواندن نیست.");val m=requireNotNull(manifest);val p=requireNotNull(products);require(m.products==p.size);require(m.images==media.size);return CreateReadPackage(m,p,media,globals)}
 private fun readLimited(input:ZipInputStream,max:Long,onBytes:(Long)->Unit):ByteArray{val out=ByteArrayOutputStream();val b=ByteArray(DEFAULT_BUFFER_SIZE);var total=0L;while(true){val n=input.read(b);if(n<=0)break;total+=n;require(total<=max);onBytes(n.toLong());out.write(b,0,n)};return out.toByteArray()}
 private suspend fun allProducts(s:StoreId):List<Product>{val out=mutableListOf<Product>();var p=1;while(true){val b=when(val r=d.getProducts(s,p,100,null)){is CoreResult.Success->r.value;is CoreResult.Failure->error("دریافت محصولات ناموفق بود: ${r.error}")};if(b.isEmpty())break;out+=b;if(b.size<100)break;p++};return out.distinctBy{it.id.value}}
 private suspend fun allVars(s:StoreId,id:EntityId):List<Variation>{val out=mutableListOf<Variation>();var p=1;while(true){val b=when(val r=d.getVariations(s,id,p,100)){is CoreResult.Success->r.value;is CoreResult.Failure->error("دریافت Variationها ناموفق بود: ${r.error}")};if(b.isEmpty())break;out+=b;if(b.size<100)break;p++};return out.distinctBy{it.id.value}}
 private suspend fun allCategories(s:StoreId):List<IdName>{val out=mutableListOf<IdName>();var p=1;while(true){val b=when(val r=d.getProductCategories(s,p,100,null)){is CoreResult.Success->r.value;is CoreResult.Failure->break};if(b.isEmpty())break;out+=b;if(b.size<100)break;p++};return out.distinctBy{it.id.value}}
 private fun categoryPath(c:IdName,byId:Map<String,IdName>):String{val parent=c.parentId?.value?.let(byId::get);return if(parent==null)normalize(c.name) else categoryPath(parent,byId)+">"+normalize(c.name)}
 private suspend fun resolveCategories(s:StoreId,source:List<CreateIdName>,byId:MutableMap<String,IdName>,byPath:MutableMap<String,IdName>,errors:MutableList<String>,onResolved:()->Unit):List<IdName>{val sourceById=source.associateBy{it.id};suspend fun r(c:CreateIdName):IdName?{val parent=c.parentId?.let(sourceById::get)?.let{r(it)};val path=(parent?.let{normalize(it.name)+">"}?:"")+normalize(c.name);byPath[path]?.let{onResolved();return it};val existing=when(val q=d.getProductCategories(s,1,100,c.name)){is CoreResult.Success->q.value.firstOrNull{normalize(it.name)==normalize(c.name)&&it.parentId?.value==parent?.id?.value};is CoreResult.Failure->null};if(existing!=null){onResolved();return existing};return when(val q=d.getProductCategories.create(s,IdName(EntityId(NEW_ID),c.name,parent?.id))){is CoreResult.Success->{onResolved();byId[q.value.id.value]=q.value;byPath[path]=q.value;q.value};is CoreResult.Failure->{errors+="دسته‌بندی «${c.name}» ساخته نشد: ${q.error}";null}}};return source.mapNotNull{r(it)}}
 private fun ext(v:String)=v.substringBefore('?').substringAfterLast('.','jpg').lowercase(Locale.ROOT).let{if(it in setOf("jpg","jpeg","png","webp","gif"))it else "jpg"};private fun mime(v:String)=when(ext(v)){"png"->"image/png";"webp"->"image/webp";"gif"->"image/gif";else->"image/jpeg"}
}
private fun CreateProduct.toDomain(id:EntityId,images:List<ProductImage>,categories:List<IdName>,attrs:List<Attribute>,sku:String?)=Product(id,name,sku,description,shortDescription,runCatching{ProductStatus.valueOf(status)}.getOrDefault(ProductStatus.DRAFT),runCatching{ProductType.valueOf(type)}.getOrDefault(ProductType.SIMPLE),Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock)else null,images,categories,attrs,null)
private fun CreateVariation.toDomain(productId:EntityId,image:ProductImage?,sku:String?)=Variation(EntityId(NEW_ID),productId,attributes.map{VariationAttribute(it.name,it.option)},Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock)else null,sku,image,null)
