package com.samanramezani1377.woogit.presentation.settings

import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.model.*
import kotlinx.datetime.Instant

internal fun Product.toTransfer(images:List<TransferImage>,variations:List<TransferVariation>)=TransferProduct(id.value,name,sku,description,shortDescription,status.name,type.name,pricing.regular,pricing.sale,pricing.onSale,stock?.quantity,stock?.status?.name,stock?.manageStock?:false,categories.map{TransferCategory(it.id.value,it.name,it.parentId?.value)},attributes.map{TransferAttribute(it.id?.value,it.name,it.visible,it.variation,it.options)},images,variations,modifiedAt)
internal fun TransferProduct.toDomain(id:EntityId,images:List<ProductImage>,categories:List<IdName>,attributes:List<Attribute>)=Product(id,name,sku,description,shortDescription,runCatching{ProductStatus.valueOf(status)}.getOrDefault(ProductStatus.DRAFT),runCatching{ProductType.valueOf(type)}.getOrDefault(ProductType.SIMPLE),Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock) else null,images,categories,attributes,modifiedAt)
internal fun Variation.toTransfer(imageWriter:(ProductImage)->String)=TransferVariation(id.value,sku,pricing.regular,pricing.sale,pricing.onSale,stock?.quantity,stock?.status?.name,stock?.manageStock?:false,attributes.map{TransferVariationAttribute(it.name,it.option)},image?.let{TransferImage(it.id?.value,it.src,it.name,it.alt,imageWriter(it))},modifiedAt?.toString())
internal fun TransferVariation.toDomain(productId:EntityId,id:EntityId,image:ProductImage?)=Variation(id,productId,attributes.map{VariationAttribute(it.name,it.option)},Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock) else null,sku,image,modifiedAt?.let{runCatching{Instant.parse(it)}.getOrNull()})