package com.samanramezani1377.woogit.presentation.settings

import android.content.ContentResolver
import android.net.Uri
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.presentation.V1PresentationDependencies
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.net.HttpURLConnection
import java.net.URL
import java.text.SimpleDateFormat
import java.util.*
import java.util.zip.*

private val json=Json{prettyPrint=true;ignoreUnknownKeys=true;explicitNulls=false}
private const val FORMAT="woogit-products";private const val VERSION=1
@Serializable private data class Manifest(val format:String=FORMAT,val version:Int=VERSION,val source:String,val exportedAt:String,val products:Int,val images:Int)
@Serializable private data class Package(val manifest:Manifest,val products:List<P>)
@Serializable private data class P(val id:String,val name:String,val sku:String?=null,val description:String?=null,val shortDescription:String?=null,val status:String,val type:String,val regular:String?=null,val sale:String?=null,val onSale:Boolean,val quantity:Double?=null,val stockStatus:String?=null,val manageStock:Boolean,val categories:List<IdNameX>=emptyList(),val attributes:List<AttrX>=emptyList(),val images:List<ImageX>=emptyList(),val variations:List<V>=emptyList(),val modifiedAt:String?=null)
@Serializable private data class V(val id:String,val sku:String?=null,val regular:String?=null,val sale:String?=null,val onSale:Boolean,val quantity:Double?=null,val stockStatus:String?=null,val manageStock:Boolean,val attributes:List<VA>=emptyList(),val image:ImageX?=null,val modifiedAt:String?=null)
@Serializable private data class VA(val name:String,val option:String)
@Serializable private data class IdNameX(val id:String,val name:String)
@Serializable private data class AttrX(val id:String?=null,val name:String,val visible:Boolean,val variation:Boolean,val options:List<String>)
@Serializable private data class ImageX(val id:String?=null,val src:String,val name:String?=null,val alt:String?=null,val file:String)
data class ProductTransferResult(val created:Int=0,val updated:Int=0,val failed:Int=0,val imagesUploaded:Int=0,val variationsCreated:Int=0,val variationsUpdated:Int=0,val errors:List<String>=emptyList())

class ProductTransferService(private val d:V1PresentationDependencies,private val resolver:ContentResolver){
 suspend fun export(storeId:StoreId,destination:Uri,onProgress:(ProductTransferProgress)->Unit={}):Result<Int>=runCatching{
  val store=when(val r=d.getStore(storeId)){is CoreResult.Success->r.value;is CoreResult.Failure->error("دریافت اطلاعات فروشگاه ناموفق بود.")};val ps=allProducts(storeId,onProgress);val files=linkedMapOf<String,ByteArray>();val out=ps.mapIndexed{ix,p->onProgress(ProductTransferProgress("در حال آماده‌سازی محصولات…",ix+1,ps.size));val imgs=p.images.mapIndexed{n,i->val f="media/p-${p.id.value}-$n.${ext(i.src)}";getBytes(i.src)?.let{files[f]=it};ImageX(i.id?.value,i.src,i.name,i.alt,f)};val vars=if(p.type==ProductType.VARIABLE)allVars(storeId,p.id).map{v->v.toX{im->val f="media/v-${v.id.value}.${ext(im.src)}";getBytes(im.src)?.let{files[f]=it};f}}else emptyList();p.toX(imgs,vars)};val m=Manifest(source=store.baseUrl.trimEnd('/'),exportedAt=SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(Date()),products=out.size,images=files.size);resolver.openOutputStream(destination)?.use{ZipOutputStream(it).use{z->z.putNextEntry(ZipEntry("manifest.json"));z.write(json.encodeToString(m).toByteArray());z.closeEntry();z.putNextEntry(ZipEntry("products.json"));z.write(json.encodeToString(Package(m,out)).toByteArray());z.closeEntry();files.forEach{(p,b)->z.putNextEntry(ZipEntry(p));z.write(b);z.closeEntry()}}}?:error("امکان ایجاد فایل خروجی وجود ندارد.");out.size}
 suspend fun import(storeId:StoreId,source:Uri,onProgress:(ProductTransferProgress)->Unit={}):ProductTransferResult=try{
  val pack=read(source);require(pack.manifest.format==FORMAT){"فرمت فایل WooGit معتبر نیست."};require(pack.manifest.version<=VERSION){"نسخه فایل پشتیبانی نمی‌شود."};val store=when(val r=d.getStore(storeId)){is CoreResult.Success->r.value;is CoreResult.Failure->return ProductTransferResult(failed=1,errors=listOf("فروشگاه در دسترس نیست."))};val same=pack.manifest.source.trimEnd('/').equals(store.baseUrl.trimEnd('/'),true);val existing=allProducts(storeId,onProgress);val byId=existing.associateBy{it.id.value};val bySku=existing.mapNotNull{it.sku?.trim()?.takeIf(String::isNotBlank)?.let{x->x to it}}.toMap();val cats=when(val r=d.getProductCategories(storeId,1,100,null)){is CoreResult.Success->r.value;is CoreResult.Failure->emptyList()};val cb=cats.associateBy{it.name.trim().lowercase()};var c=0;var u=0;var f=0;var iu=0;var vc=0;var vu=0;val errors=mutableListOf<String>();pack.products.forEachIndexed{ix,x->onProgress(ProductTransferProgress("در حال وارد کردن محصولات…",ix+1,pack.products.size));try{val old=if(same)byId[x.id]?:x.sku?.let{bySku[it.trim()]}else x.sku?.trim()?.takeIf(String::isNotBlank)?.let(bySku::get);val imgs=x.images.mapNotNull{im->pack.files[im.file]?.let{b->when(val r=d.uploadMedia(storeId,im.file.substringAfterLast('/'),b,mime(im.file))){is CoreResult.Success->{iu++;r.value};is CoreResult.Failure->{errors+="${x.name}: تصویر وارد نشد";null}}}};val cs=x.categories.mapNotNull{cat->cb[cat.name.trim().lowercase()]?:if(same)IdName(EntityId(cat.id),cat.name)else null};val p=x.toDomain(old?.id,imgs,cs);val saved=if(old==null)d.createProduct(storeId,p)else d.updateProduct(storeId,old.id,p.copy(id=old.id));val sp=when(saved){is CoreResult.Success->{if(old==null)c++else u++;saved.value};is CoreResult.Failure->{f++;errors+="${x.name}: ${saved.error}";return@forEachIndexed}};val ev=allVars(storeId,sp.id);x.variations.forEach{vv->val ov=if(same)ev.firstOrNull{it.id.value==vv.id}?:vv.sku?.let{s->ev.firstOrNull{it.sku?.trim()==s.trim()}}else vv.sku?.let{s->ev.firstOrNull{it.sku?.trim()==s.trim()}};val vi=vv.image?.let{im->pack.files[im.file]?.let{b->when(val r=d.uploadMedia(storeId,im.file.substringAfterLast('/'),b,mime(im.file))){is CoreResult.Success->{iu++;r.value};is CoreResult.Failure->null}}};val v=vv.toDomain(sp.id,ov?.id,vi);when(val r=if(ov==null)d.createVariation(storeId,v)else d.updateVariation(storeId,sp.id,ov.id,v.copy(id=ov.id))){is CoreResult.Success->if(ov==null)vc++else vu++;is CoreResult.Failure->errors+="${x.name}: variation ${vv.sku?:vv.id} وارد نشد"}}}catch(t:Throwable){f++;errors+="${x.name}: ${t.message?:"خطای نامشخص"}"}};ProductTransferResult(c,u,f,iu,vc,vu,errors.take(50))}catch(t:Throwable){ProductTransferResult(failed=1,errors=listOf(t.message?:"خواندن فایل ناموفق بود."))}
 private suspend fun allProducts(s:StoreId,p:(ProductTransferProgress)->Unit):List<Product>{val a=mutableListOf<Product>();var page=1;while(true){val r=d.getProducts(s,page,100,null);val b=when(r){is CoreResult.Success->r.value;is CoreResult.Failure->break};if(b.isEmpty())break;a+=b;p(ProductTransferProgress("در حال دریافت محصولات…",a.size,a.size));if(b.size<100)break;page++};return a.distinctBy{it.id.value}}
 private suspend fun allVars(s:StoreId,id:EntityId):List<Variation>{val a=mutableListOf<Variation>();var page=1;while(true){val r=d.getVariations(s,id,page,100);val b=when(r){is CoreResult.Success->r.value;is CoreResult.Failure->break};if(b.isEmpty())break;a+=b;if(b.size<100)break;page++};return a.distinctBy{it.id.value}}
 private fun read(u:Uri):PF{var m:Manifest?=null;var ps:List<P>?=null;val fs=linkedMapOf<String,ByteArray>();resolver.openInputStream(u)?.use{ZipInputStream(it).use{z->while(true){val e=z.nextEntry?:break;if(e.isDirectory)continue;val b=z.readBytes();when(e.name){"manifest.json"->m=json.decodeFromString<Manifest>(b.toString(Charsets.UTF_8));"products.json"->{val q=json.decodeFromString<Package>(b.toString(Charsets.UTF_8));m=m?:q.manifest;ps=q.products};else->if(e.name.startsWith("media/"))fs[e.name]=b}}}}?:error("فایل قابل خواندن نیست");return PF(requireNotNull(m),requireNotNull(ps),fs)}
 private data class PF(val manifest:Manifest,val products:List<P>,val files:Map<String,ByteArray>)
 private fun getBytes(src:String):ByteArray?=try{val c=URL(src).openConnection() as HttpURLConnection;c.connectTimeout=15000;c.readTimeout=30000;c.instanceFollowRedirects=true;c.inputStream.use{it.readBytes()}.also{c.disconnect()}}catch(_:Throwable){null}
 private fun ext(s:String)=s.substringBefore('?').substringAfterLast('.','jpg').lowercase().let{if(it in setOf("jpg","jpeg","png","webp","gif"))it else "jpg"}
 private fun mime(s:String)=when(ext(s)){"png"->"image/png";"webp"->"image/webp";"gif"->"image/gif";else->"image/jpeg"}
}
private fun Product.toX(i:List<ImageX>,v:List<V>)=P(id.value,name,sku,description,shortDescription,status.name,type.name,pricing.regular,pricing.sale,pricing.onSale,stock?.quantity,stock?.status?.name,stock?.manageStock,categories.map{IdNameX(it.id.value,it.name)},attributes.map{AttrX(it.id?.value,it.name,it.visible,it.variation,it.options)},i,v,modifiedAt)
private fun P.toDomain(id:EntityId?,imgs:List<ProductImage>,cats:List<IdName>)=Product(id?:EntityId(this.id),name,sku,description,shortDescription,runCatching{ProductStatus.valueOf(status)}.getOrDefault(ProductStatus.DRAFT),runCatching{ProductType.valueOf(type)}.getOrDefault(ProductType.SIMPLE),Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock)else null,imgs,cats,attributes.map{Attribute(it.id?.let(::EntityId),it.name,it.visible,it.variation,it.options)},modifiedAt)
private fun Variation.toX(file:(ProductImage)->String)=V(id.value,sku,pricing.regular,pricing.sale,pricing.onSale,stock?.quantity,stock?.status?.name,stock?.manageStock,attributes.map{VA(it.name,it.option)},image?.let{ImageX(it.id?.value,it.src,it.name,it.alt,file(it))},modifiedAt?.toString())
private fun V.toDomain(pid:EntityId,id:EntityId?,im:ProductImage?)=Variation(id?:EntityId(this.id),pid,attributes.map{VariationAttribute(it.name,it.option)},Pricing(regular,sale,onSale),if(quantity!=null||stockStatus!=null||manageStock)Stock(quantity,runCatching{StockStatus.valueOf(stockStatus?:StockStatus.IN_STOCK.name)}.getOrDefault(StockStatus.IN_STOCK),manageStock)else null,sku,im,modifiedAt?.let{runCatching{kotlinx.datetime.Instant.parse(it)}.getOrNull()})
