package com.samanramezani1377.woogit.presentation.commerce

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.samanramezani1377.woogit.core.domain.commerce.*
import com.samanramezani1377.woogit.presentation.GlassCard
import com.samanramezani1377.woogit.presentation.GlassTokens
import kotlin.math.roundToInt

@Composable internal fun OverviewCard(analytics: AnalyticsSnapshot, range: AnalyticsRange) = Section("نمای کلی فروش", "شاخص‌های اصلی در بازه ${range.label}.") { MetricGrid(listOf("فروش تکمیل‌شده" to formatNumber(analytics.sales), "سفارش‌های تکمیل‌شده" to analytics.completedOrders.toString(), "کل سفارش‌ها" to analytics.totalOrders.toString(), "میانگین ارزش سفارش" to formatNumber(analytics.averageOrderValue))) }

@Composable internal fun ComparisonCard(analytics: AnalyticsSnapshot) = Section("مقایسه با دوره قبل", "همان بازه زمانی قبل.") { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) { GrowthRow("فروش", analytics.salesGrowthPercent); GrowthRow("تعداد سفارش", analytics.orderGrowthPercent); GrowthRow("میانگین ارزش سفارش", analytics.averageOrderGrowthPercent); Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) { MetricCard("فروش دوره قبل", formatNumber(analytics.previousSales), Modifier.weight(1f)); MetricCard("سفارش دوره قبل", analytics.previousOrders.toString(), Modifier.weight(1f)) } } }

@Composable internal fun GrowthRow(label: String, value: Double?) { GlassCard(Modifier.fillMaxWidth()) { Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) { Column(Modifier.weight(1f)) { Text(label, fontWeight = FontWeight.SemiBold); Text("نسبت به دوره قبل", color = GlassTokens.muted, style = MaterialTheme.typography.labelSmall) }; Text(formatPercent(value), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.titleMedium) } } }

@Composable internal fun TrendSection(analytics: AnalyticsSnapshot) { Section("روند فروش", "مقایسه روزبه‌روز دوره فعلی با دوره قبل.") { ComparisonTrendChart(analytics.currentTrend, analytics.previousTrend, sales = true) }; Section("روند سفارش‌ها", "مقایسه روزبه‌روز تعداد سفارش‌های فعلی با دوره قبل.") { ComparisonTrendChart(analytics.currentTrend, analytics.previousTrend, sales = false) } }

@Composable internal fun CompletionCard(analytics: AnalyticsSnapshot) = Section("نرخ تکمیل سفارش", "سهم سفارش‌های تکمیل‌شده از کل سفارش‌های بازه.") { GlassCard(Modifier.fillMaxWidth()) { Text("${analytics.completionRate.roundToInt()}٪", style = MaterialTheme.typography.displaySmall, fontWeight = FontWeight.Bold); Spacer(Modifier.height(8.dp)); ProgressBar(analytics.completionRate / 100.0); Spacer(Modifier.height(8.dp)); Text("${analytics.completedOrders} سفارش از ${analytics.totalOrders} سفارش تکمیل شده است.", color = GlassTokens.muted, style = MaterialTheme.typography.bodySmall) } }

@Composable internal fun StatusBreakdownCard(analytics: AnalyticsSnapshot) { if (analytics.statusCounts.isEmpty()) return; Section("تفکیک وضعیت سفارش‌ها", "تعداد، سهم و مبلغ سفارش‌ها بر اساس وضعیت.") { val maxCount = analytics.statusCounts.values.maxOrNull()?.coerceAtLeast(1) ?: 1; GlassCard(Modifier.fillMaxWidth()) { analytics.statusCounts.entries.sortedByDescending { it.value }.forEachIndexed { index, (status, count) -> val share = if (analytics.totalOrders == 0) 0.0 else count * 100.0 / analytics.totalOrders; StatusBreakdownRow(status.faLabel(), count, share, analytics.statusRevenue[status] ?: 0.0, count.toDouble() / maxCount); if (index < analytics.statusCounts.size - 1) Spacer(Modifier.height(10.dp)) } } } }

@Composable internal fun StatusBreakdownRow(label: String, count: Int, share: Double, amount: Double, relative: Double) { Column { Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) { Text(label, fontWeight = FontWeight.SemiBold, modifier = Modifier.weight(1f)); Text("$count سفارش", color = GlassTokens.muted, style = MaterialTheme.typography.labelSmall) }; Spacer(Modifier.height(5.dp)); ProgressBar(relative); Spacer(Modifier.height(4.dp)); Row(horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) { Text("${share.roundToInt()}٪", color = GlassTokens.muted, style = MaterialTheme.typography.labelSmall); Text(formatNumber(amount), fontWeight = FontWeight.Bold, style = MaterialTheme.typography.labelSmall) } } }

@Composable internal fun ProductBreakdownCard(analytics: AnalyticsSnapshot) { if (analytics.productAnalytics.isEmpty()) return; Section("محصولات برتر", "رتبه‌بندی بر اساس درآمد و سهم از فروش.") { GlassCard(Modifier.fillMaxWidth()) { analytics.productAnalytics.take(10).forEachIndexed { index, product -> RankedRow(index + 1, product.name, "${formatNumber(product.quantity)} عدد", formatNumber(product.revenue), product.sharePercent / 100.0); if (index < analytics.productAnalytics.take(10).lastIndex) Spacer(Modifier.height(10.dp)) } } } }

@Composable internal fun CustomerInsightsCard(analytics: AnalyticsSnapshot) { if (analytics.customerAnalytics.isEmpty()) return; Section("بینش مشتری‌ها", "مشتریان جدید، تکراری و ارزش خرید.") { MetricGrid(listOf("تعداد مشتریان" to analytics.uniqueCustomers.toString(), "مشتریان جدید" to analytics.newCustomers.toString(), "مشتریان تکراری" to analytics.repeatCustomers.toString(), "میانگین خرید مشتری" to formatNumber(analytics.averageCustomerSpend))); Spacer(Modifier.height(8.dp)); GlassCard(Modifier.fillMaxWidth()) { analytics.customerAnalytics.take(10).forEachIndexed { index, customer -> RankedRow(index + 1, customer.name + if (customer.isNew) " • جدید" else "", "${customer.orderCount} سفارش", formatNumber(customer.totalSpent)); if (index < analytics.customerAnalytics.take(10).lastIndex) Spacer(Modifier.height(10.dp)) } } } }

@Composable internal fun CouponPerformanceCard(analytics: AnalyticsSnapshot) { if (analytics.couponAnalytics.isEmpty()) return; Section("عملکرد کوپن‌ها", "استفاده، تخفیف و فروش ایجادشده.") { analytics.couponAnalytics.maxByOrNull { it.generatedSales }?.let { GlassCard(Modifier.fillMaxWidth()) { Text("پربازده‌ترین کوپن", color = GlassTokens.muted, style = MaterialTheme.typography.labelSmall); Spacer(Modifier.height(3.dp)); Text(it.code, style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold); Text(formatNumber(it.generatedSales), style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold); Text("فروش ایجادشده", color = GlassTokens.muted, style = MaterialTheme.typography.bodySmall) } }; Spacer(Modifier.height(8.dp)); GlassCard(Modifier.fillMaxWidth()) { val maxSales = analytics.couponAnalytics.maxOfOrNull { it.generatedSales }?.coerceAtLeast(1.0) ?: 1.0; analytics.couponAnalytics.take(10).forEachIndexed { index, coupon -> Column { Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) { Text("${index + 1}. ${coupon.code}", fontWeight = FontWeight.SemiBold, modifier = Modifier.weight(1f)); Text(formatNumber(coupon.generatedSales), fontWeight = FontWeight.Bold) }; Spacer(Modifier.height(5.dp)); ProgressBar(coupon.generatedSales / maxSales); Spacer(Modifier.height(3.dp)); Text("${coupon.usageCount} استفاده • تخفیف ${formatNumber(coupon.discountTotal)}", color = GlassTokens.muted, style = MaterialTheme.typography.labelSmall) }; if (index < analytics.couponAnalytics.take(10).lastIndex) Spacer(Modifier.height(10.dp)) } } } }

@Composable internal fun InventoryHealthCard(analytics: AnalyticsSnapshot) = Section("سلامت موجودی", "وضعیت کلی موجودی محصولات.") { GlassCard(Modifier.fillMaxWidth()) { HealthRow("کل محصولات", analytics.inventoryProducts, analytics.inventoryProducts.coerceAtLeast(1)); Spacer(Modifier.height(10.dp)); HealthRow("موجودی کم", analytics.lowStockProducts, analytics.inventoryProducts.coerceAtLeast(1)); Spacer(Modifier.height(10.dp)); HealthRow("ناموجود", analytics.outOfStockProducts, analytics.inventoryProducts.coerceAtLeast(1)) } }

@Composable internal fun HealthRow(label: String, value: Int, total: Int) { Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.fillMaxWidth()) { Column(Modifier.weight(1f)) { Text(label, fontWeight = FontWeight.SemiBold); Spacer(Modifier.height(4.dp)); ProgressBar(value.toDouble() / total.coerceAtLeast(1)) }; Spacer(Modifier.width(12.dp)); Text(value.toString(), style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold) } }

internal fun formatPercent(value: Double?): String = value?.let { "${if (it >= 0) "+" else ""}${it.roundToInt()}٪" } ?: "—"
