package com.samanramezani1377.woogit.presentation

import android.app.Activity
import androidx.activity.compose.BackHandler
import androidx.compose.runtime.*
import androidx.compose.ui.platform.LocalContext
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavType
import androidx.navigation.compose.*
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.presentation.ai.AiScreen
import com.samanramezani1377.woogit.presentation.connection.ConnectionScreen
import com.samanramezani1377.woogit.presentation.dashboard.*
import com.samanramezani1377.woogit.presentation.order.*
import com.samanramezani1377.woogit.presentation.orders.*
import com.samanramezani1377.woogit.presentation.product.*
import com.samanramezani1377.woogit.presentation.settings.SettingsScreen
import com.samanramezani1377.woogit.presentation.sync.*

@Composable
internal fun E11AppNavigation(dependencies: V1PresentationDependencies, initialOrderId: String?) {
    val navController = rememberNavController()
    var activeStore by remember { mutableStateOf(dependencies.initialStoreId) }
    val context = LocalContext.current
    val currentRoute by navController.currentBackStackEntryAsState()
    val route = currentRoute?.destination?.route
    LaunchedEffect(dependencies.initialStoreId) { dependencies.initialStoreId?.let { persistedStore -> if (activeStore != persistedStore) activeStore = persistedStore } }
    BackHandler(enabled = route != E11Routes.CONNECTION) { if (navController.previousBackStackEntry != null) navController.popBackStack() else (context as? Activity)?.moveTaskToBack(true) }
    val startDestination = when { activeStore == null -> E11Routes.CONNECTION; initialOrderId != null -> E11Routes.order(initialOrderId); else -> E11Routes.DASHBOARD }
    NavHost(navController, startDestination) {
        composable(E11Routes.CONNECTION) { ConnectionScreen(dependencies) { storeId -> activeStore = storeId; dependencies.onStoreConnected(storeId); navController.navigate(E11Routes.DASHBOARD) { popUpTo(E11Routes.CONNECTION) { inclusive = true } } } }
        composable(E11Routes.DASHBOARD) { val store = activeStore; if (store != null) { val storeId = StoreId(store); val vm = viewModel<DashboardViewModel>(key = "dashboard-${storeId.value}", factory = DashboardViewModelFactory(dependencies, storeId)); val state by vm.uiState.collectAsState(); LaunchedEffect(storeId) { vm.refresh() }; DisposableEffect(vm, storeId) { vm.startConnectionHealthMonitor(); onDispose { vm.stopConnectionHealthMonitor() } }; val recent = state.orders.firstOrNull(); DashboardScreen(storeId.value, state.connectionState == ConnectionState.CONNECTED, state.ordersCount, state.productsCount, state.revenue, state.processingCount, recent?.number, recent?.customer?.name.orEmpty(), formatMoney(recent?.total), recent?.status, { recent?.number?.let { navController.navigate(E11Routes.order(it)) } }, { navController.navigate(E11Routes.ORDERS) }, { navController.navigate(E11Routes.PRODUCTS) }, { navController.navigate(E11Routes.SETTINGS) }, { navController.navigate(E11Routes.SYNC) }, { navController.navigate(E11Routes.CONFLICTS) }, DashboardDestination.DASHBOARD, { destination -> when (destination) { DashboardDestination.DASHBOARD -> Unit; DashboardDestination.ORDERS -> navController.navigate(E11Routes.ORDERS); DashboardDestination.PRODUCTS -> navController.navigate(E11Routes.PRODUCTS); DashboardDestination.SETTINGS -> navController.navigate(E11Routes.SETTINGS) } }, { navController.navigate(E11Routes.AI) }) } }
        composable(E11Routes.AI) { AiScreen() }
        composable(E11Routes.ORDERS) { val store = activeStore; if (store != null) { val storeId = StoreId(store); val vm = viewModel<OrdersViewModel>(key = "orders-${storeId.value}", factory = vmFactory { OrdersViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId) { vm.load(storeId) }; OrdersScreen(mapOrdersState(state, vm.hasMore()), { id -> navController.navigate(E11Routes.order(id)) }, { vm.load(storeId) }, { vm.nextPage(storeId) }, { vm.load(storeId, it, true) }) } }
        composable(E11Routes.ORDER_DETAIL, listOf(navArgument(E11Routes.ORDER_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val id = entry.arguments?.getString(E11Routes.ORDER_ID); if (store != null && id != null) { val storeId = StoreId(store); val vm = viewModel<OrderDetailViewModel>(key = "order-detail-${storeId.value}-$id", factory = vmFactory { OrderDetailViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId, id) { vm.load(storeId, EntityId(id)) }; OrderDetailScreen(mapOrderDetailState(state), { vm.load(storeId, EntityId(id)) }, { navController.popBackStack() }, { status -> vm.updateStatus(storeId, status) }) } }
        composable(E11Routes.PRODUCTS) { val store = activeStore; if (store != null) { val storeId = StoreId(store); val vm = viewModel<ProductsViewModel>(key = "products-${storeId.value}", factory = vmFactory { ProductsViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId) { vm.load(storeId) }; ProductsScreen(state, { id -> navController.navigate(E11Routes.product(id)) }, { vm.load(storeId) }, { vm.nextPage(storeId) }, { vm.load(storeId, it, true) }, { navController.navigate(E11Routes.PRODUCT_NEW) }) } }
        composable(E11Routes.PRODUCT_DETAIL, listOf(navArgument(E11Routes.PRODUCT_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val id = entry.arguments?.getString(E11Routes.PRODUCT_ID); if (store != null && id != null) { val storeId = StoreId(store); val vm = viewModel<ProductDetailViewModel>(key = "product-detail-${storeId.value}-$id", factory = vmFactory { ProductDetailViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId, id) { vm.load(storeId, EntityId(id)) }; when (val current = state) { is FeatureUiState.Success -> ProductDetailScreen(current.value, { navController.popBackStack() }, { navController.navigate(E11Routes.productEdit(id)) }, { navController.navigate(E11Routes.variations(id)) }); FeatureUiState.Loading, FeatureUiState.Pending -> GlassScaffold { GlassLoading("در حال بارگذاری محصول…") }; FeatureUiState.Empty -> GlassScaffold { GlassEmptyState("محصول پیدا نشد") }; is FeatureUiState.Error -> GlassScaffold { GlassErrorState(current.message) }; FeatureUiState.Offline -> GlassScaffold { GlassOfflineState() }; is FeatureUiState.Conflict -> GlassScaffold { GlassErrorState("تعارض در داده‌های محصول وجود دارد") } } } }
        composable(E11Routes.PRODUCT_NEW) { activeStore?.let { ProductEditorRoute(dependencies, StoreId(it), null, { navController.popBackStack() }, { navController.popBackStack() }) } }
        composable(E11Routes.PRODUCT_EDIT, listOf(navArgument(E11Routes.PRODUCT_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val id = entry.arguments?.getString(E11Routes.PRODUCT_ID); if (store != null && id != null) ProductEditorRoute(dependencies, StoreId(store), id, { navController.popBackStack() }, { navController.popBackStack() }) }
        composable(E11Routes.VARIATIONS, listOf(navArgument(E11Routes.PRODUCT_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val id = entry.arguments?.getString(E11Routes.PRODUCT_ID); if (store != null && id != null) { val storeId = StoreId(store); val vm = viewModel<VariationsViewModel>(key = "variations-${storeId.value}-$id", factory = vmFactory { VariationsViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId, id) { vm.load(storeId, EntityId(id)) }; val list = (state as? FeatureUiState.Success)?.value.orEmpty().map { variation -> VariationUiModel(variation.id.value, variation.attributes.joinToString(" · ") { "${it.name}: ${it.option}" }, variation.pricing.sale ?: variation.pricing.regular ?: "—", variation.stock?.quantity?.toString()?.removeSuffix(".0") ?: "—") }; VariationsManagementScreen(list, { navController.navigate(E11Routes.variationNew(id)) }, { variationId -> navController.navigate(E11Routes.variationEdit(id, variationId)) }) } }
        composable(E11Routes.VARIATION_NEW, listOf(navArgument(E11Routes.PRODUCT_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val id = entry.arguments?.getString(E11Routes.PRODUCT_ID); if (store != null && id != null) VariationEditorRoute(dependencies, StoreId(store), id, null, { navController.popBackStack() }, { navController.popBackStack() }) }
        composable(E11Routes.VARIATION_EDIT, listOf(navArgument(E11Routes.PRODUCT_ID) { type = NavType.StringType }, navArgument(E11Routes.VARIATION_ID) { type = NavType.StringType })) { entry -> val store = activeStore; val productId = entry.arguments?.getString(E11Routes.PRODUCT_ID); val variationId = entry.arguments?.getString(E11Routes.VARIATION_ID); if (store != null && productId != null && variationId != null) VariationEditorRoute(dependencies, StoreId(store), productId, variationId, { navController.popBackStack() }, { navController.popBackStack() }) }
        composable(E11Routes.SYNC) { val store = activeStore; if (store != null) { val storeId = StoreId(store); val vm = viewModel<SyncViewModel>(key = "sync-${storeId.value}", factory = vmFactory { SyncViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId) { vm.load(storeId) }; SyncScreen(mapSyncState(state), { vm.sync(storeId) }, { vm.sync(storeId) }) } }
        composable(E11Routes.CONFLICTS) { val store = activeStore; if (store != null) { val storeId = StoreId(store); val vm = viewModel<ConflictsViewModel>(key = "conflicts-${storeId.value}", factory = vmFactory { ConflictsViewModel(dependencies) }); val state by vm.state.collectAsState(); LaunchedEffect(storeId) { vm.load(storeId) }; val list = (state as? FeatureUiState.Success)?.value.orEmpty().map { conflict -> ConflictUiModel(conflict.id.value, "${conflict.entityType} · ${conflict.reason}", conflict.localSnapshot ?: conflict.localVersion?.value ?: "—", conflict.serverSnapshot ?: conflict.remoteVersion?.value ?: "—") }; ConflictsScreen(list, { id -> vm.resolve(storeId, EntityId(id), ConflictResolution.KEEP_LOCAL) }, { id -> vm.resolve(storeId, EntityId(id), ConflictResolution.KEEP_SERVER) }) } }
        composable(E11Routes.SETTINGS) { val store = activeStore; if (store != null) SettingsScreen(storeName = store, storeId = StoreId(store), dependencies = dependencies, onBack = { navController.popBackStack() }, onDisconnect = { dependencies.onStoreDisconnected(); activeStore = null; navController.navigate(E11Routes.CONNECTION) { popUpTo(E11Routes.SETTINGS) { inclusive = true } } }) }
    }
}

private fun mapOrdersState(state: FeatureUiState<List<Order>>, hasMore: Boolean): OrdersUiState = when (state) { FeatureUiState.Loading, FeatureUiState.Pending -> OrdersUiState.Loading; FeatureUiState.Empty -> OrdersUiState.Empty; is FeatureUiState.Error -> OrdersUiState.Error(state.message, state.retryable); FeatureUiState.Offline -> OrdersUiState.Offline(); is FeatureUiState.Conflict -> OrdersUiState.Error("تعارض در داده‌های سفارش وجود دارد.", false); is FeatureUiState.Success -> OrdersUiState.Content(state.value.map { order -> OrderRowUiModel(order.number, order.customer?.name.orEmpty(), order.customer?.email.orEmpty(), order.status.name, formatMoney(order.total), order.payment?.methodTitle.orEmpty(), order.modifiedAt?.toString().orEmpty()) }, hasMore) }
private fun mapOrderDetailState(state: FeatureUiState<Order>): OrderDetailUiState = when (state) { FeatureUiState.Loading, FeatureUiState.Pending -> OrderDetailUiState.Loading; FeatureUiState.Empty -> OrderDetailUiState.NotFound; is FeatureUiState.Error -> OrderDetailUiState.Error(state.message); FeatureUiState.Offline -> OrderDetailUiState.Error("سفارش در حالت آفلاین در دسترس نیست."); is FeatureUiState.Conflict -> OrderDetailUiState.Error("تعارض در داده‌های سفارش."); is FeatureUiState.Success -> OrderDetailUiState.Content(state.value) }
private fun mapSyncState(state: FeatureUiState<SyncMetadata>): SyncUiState = when (state) { FeatureUiState.Loading, FeatureUiState.Pending -> SyncUiState.Running; FeatureUiState.Empty -> SyncUiState.Idle; is FeatureUiState.Success -> SyncUiState.Success("وضعیت همگام‌سازی فروشگاه با موفقیت دریافت شد."); is FeatureUiState.Error -> SyncUiState.Error(state.message); FeatureUiState.Offline -> SyncUiState.Error("فروشگاه در حالت آفلاین در دسترس نیست."); is FeatureUiState.Conflict -> SyncUiState.Error("تعارض در داده‌های همگام‌سازی وجود دارد") }
private fun formatMoney(value: String?): String { val amount = value?.toDoubleOrNull() ?: return "—"; return "${java.text.NumberFormat.getNumberInstance(java.util.Locale.US).apply { maximumFractionDigits = 0; minimumFractionDigits = 0 }.format(amount)} تومان" }
