package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.*
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

private sealed interface FinalState<out T>{data object Loading:FinalState<Nothing>;data object Empty:FinalState<Nothing>;data class Content<T>(val value:T):FinalState<T>;data class Error(val message:String):FinalState<Nothing>}
private fun <T:ViewModel> finalVm(factory:()->T)=viewModel<T>(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <M:ViewModel>create(modelClass:Class<M>):M=factory() as M})
private fun localId(prefix:String)=EntityId("local-$prefix-${System.currentTimeMillis()}")

private class FinalListVm(private val d:V1PresentationDependencies):ViewModel(){val orders=MutableStateFlow<FinalState<List<Order>>>(FinalState.Loading);val products=MutableStateFlow<FinalState<List<Product>>>(FinalState.Loading);fun orders(s:StoreId,q:String?){viewModelScope.launch{orders.value=when(val r=d.getOrders(s,1,30,q,null)){is CoreResult.Success->if(r.value.isEmpty())FinalState.Empty else FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}};fun products(s:StoreId,q:String?){viewModelScope.launch{products.value=when(val r=d.getProducts(s,1,30,q)){is CoreResult.Success->if(r.value.isEmpty())FinalState.Empty else FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}}}
private class FinalProductVm(private val d:V1PresentationDependencies):ViewModel(){val state=MutableStateFlow<FinalState<Product>>(FinalState.Loading);fun load(s:StoreId,id:EntityId){viewModelScope.launch{state.value=when(val r=d.getProduct(s,id)){is CoreResult.Success->FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}};fun save(s:StoreId,p:Product,onDone:()->Unit){viewModelScope.launch{when(d.updateProduct(s,p.id,p)){is CoreResult.Success->onDone();is CoreResult.Failure->state.value=FinalState.Error("ذخیره محصول ناموفق بود")}}};fun create(s:StoreId,p:Product,onDone:()->Unit){viewModelScope.launch{when(d.createProduct(s,p)){is CoreResult.Success->onDone();is CoreResult.Failure->state.value=FinalState.Error("ایجاد محصول ناموفق بود")}}};fun delete(s:StoreId,id:EntityId,onDone:()->Unit){viewModelScope.launch{when(d.deleteProduct(s,id)){is CoreResult.Success->onDone();is CoreResult.Failure->state.value=FinalState.Error("حذف محصول ناموفق بود")}}}}
private class FinalVariationVm(private val d:V1PresentationDependencies):ViewModel(){val state=MutableStateFlow<FinalState<List<Variation>>>(FinalState.Loading);fun load(s:StoreId,p:EntityId){viewModelScope.launch{state.value=when(val r=d.getVariations(s,p,1,30)){is CoreResult.Success->if(r.value.isEmpty())FinalState.Empty else FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}}}
private class FinalAttributeVm(private val d:V1PresentationDependencies):ViewModel(){val state=MutableStateFlow<FinalState<List<GlobalAttribute>>>(FinalState.Loading);fun load(s:StoreId){viewModelScope.launch{state.value=when(val r=d.getAttributes(s,1,100)){is CoreResult.Success->if(r.value.isEmpty())FinalState.Empty else FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}};fun add(s:StoreId,n:String){viewModelScope.launch{d.createAttribute(s,GlobalAttribute(localId("attribute"),n,n.lowercase().replace(" ","-"),emptyList()));load(s)}}}
private class FinalTermVm(private val d:V1PresentationDependencies):ViewModel(){val state=MutableStateFlow<FinalState<List<AttributeTerm>>>(FinalState.Loading);fun load(s:StoreId,a:EntityId){viewModelScope.launch{state.value=when(val r=d.getTerms(s,a,1,100)){is CoreResult.Success->if(r.value.isEmpty())FinalState.Empty else FinalState.Content(r.value);is CoreResult.Failure->FinalState.Error(r.error.toString())}}};fun add(s:StoreId,a:EntityId,n:String){viewModelScope.launch{d.createTerm(s,a,AttributeTerm(null,n,n.lowercase().replace(" ","-")));load(s,a)}}}

@Composable fun E11FinalApp(d:V1PresentationDependencies){var store by rememberSaveable{mutableStateOf(d.initialStoreId)};val nav=rememberNavController();NavHost(nav,if(store==null)"connect" else "dashboard"){composable("connect"){Connect(d){id->store=id;nav.navigate("dashboard"){popUpTo("connect"){inclusive=true}}}};composable("dashboard"){Dashboard(d,StoreId(store!!),nav)};composable("orders"){Orders(d,StoreId(store!!),nav)};composable("order/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){OrderDetail(d,StoreId(store!!),EntityId(it.arguments!!.getString("id")!!))};composable("products"){Products(d,StoreId(store!!),nav)};composable("product/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){ProductDetail(d,StoreId(store!!),EntityId(it.arguments!!.getString("id")!!),nav)};composable("product-edit/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){ProductEdit(d,StoreId(store!!),it.arguments!!.getString("id")!!,nav)};composable("variations/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){Variations(d,StoreId(store!!),EntityId(it.arguments!!.getString("id")!!))};composable("attributes"){Attributes(d,StoreId(store!!),nav)};composable("terms/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){Terms(d,StoreId(store!!),EntityId(it.arguments!!.getString("id")!!))};composable("sync"){Sync(d,StoreId(store!!))};composable("conflicts"){Conflicts(d,StoreId(store!!))};composable("settings"){Settings(d,StoreId(store!!),nav){store=null}}}}

@Composable private fun Connect(d:V1PresentationDependencies,done:(String)->Unit){val vm=finalVm{ConnectionViewModel(d)};val state by vm.state.collectAsState();var url by rememberSaveable{mutableStateOf("")};var key by rememberSaveable{mutableStateOf("")};var secret by rememberSaveable{mutableStateOf("")};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){GlassTopBar("اتصال فروشگاه","WooCommerce");GlassTextField(url,{url=it},"Store URL");GlassTextField(key,{key=it},"Consumer Key");GlassTextField(secret,{secret=it},"Consumer Secret",secret=true);if(state is FeatureUiState.Error)GlassErrorState((state as FeatureUiState.Error).message);GlassButton("بررسی و اتصال",{vm.connect(url,key,secret)},Modifier.fillMaxWidth(),url.isNotBlank()&&key.isNotBlank()&&secret.isNotBlank());if(state is FeatureUiState.Success)done((state as FeatureUiState.Success<StoreConnection>).value.storeId.value)}}}
@Composable private fun Dashboard(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){var sync by remember{mutableStateOf("در حال بررسی…")};LaunchedEffect(s){sync=when(val r=d.getSyncState(s)){is CoreResult.Success->r.value.state.toString();is CoreResult.Failure->"نامشخص"}};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){GlassTopBar("داشبورد","Store: ${s.value}");GlassCard{Text("وضعیت همگام‌سازی");Text(sync)};GlassButton("سفارش‌ها",{nav.navigate("orders")},Modifier.fillMaxWidth());GlassButton("محصولات",{nav.navigate("products")},Modifier.fillMaxWidth());GlassButton("ویژگی‌ها",{nav.navigate("attributes")},Modifier.fillMaxWidth());GlassButton("همگام‌سازی",{nav.navigate("sync")},Modifier.fillMaxWidth());GlassButton("تعارض‌ها",{nav.navigate("conflicts")},Modifier.fillMaxWidth());GlassOutlinedButton("تنظیمات",{nav.navigate("settings")},Modifier.fillMaxWidth())}}}
@Composable private fun Orders(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=finalVm{FinalListVm(d)};val state by vm.orders.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.orders(s,q.ifBlank{null})};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("سفارش‌ها");GlassSearchField(q,{q=it},"جستجو");when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("سفارشی وجود ندارد");is FinalState.Error->GlassErrorState(x.message){vm.orders(s,q.ifBlank{null})};is FinalState.Content->LazyColumn{items(x.value){o->GlassCard(Modifier.fillMaxWidth().padding(vertical=4.dp)){Text("#${o.number}");Text("${o.status} • ${o.total.orEmpty()} ${o.currency.orEmpty()}");GlassButton("جزئیات",{nav.navigate("order/${o.id.value}")})}}}}}}}
@Composable private fun OrderDetail(d:V1PresentationDependencies,s:StoreId,id:EntityId){val vm=finalVm{OrderDetailViewModel(d)};val state by vm.state.collectAsState();var note by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,id){vm.load(s,id)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت…");FeatureUiState.Empty->GlassEmptyState("سفارش پیدا نشد");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s,id)};is FeatureUiState.Success->{GlassTopBar("سفارش #${x.value.number}");GlassCard{Text("وضعیت: ${x.value.status}");Text("مبلغ: ${x.value.total.orEmpty()} ${x.value.currency.orEmpty()}");Text("پرداخت: ${x.value.payment?.methodTitle.orEmpty()}");Text("اقلام: ${x.value.items.size}")};GlassTextField(note,{note=it},"یادداشت");GlassButton("افزودن یادداشت",{vm.note(s,id,note);note=""},Modifier.fillMaxWidth(),note.isNotBlank());GlassButton("تغییر وضعیت به Processing",{vm.update(s,x.value.copy(status=OrderStatus.PROCESSING))},Modifier.fillMaxWidth())}}}}}
@Composable private fun Products(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=finalVm{FinalListVm(d)};val state by vm.products.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.products(s,q.ifBlank{null})};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("محصولات");GlassSearchField(q,{q=it},"جستجو");GlassButton("افزودن محصول",{nav.navigate("product-edit/new")},Modifier.fillMaxWidth());when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("محصولی وجود ندارد");is FinalState.Error->GlassErrorState(x.message){vm.products(s,q.ifBlank{null})};is FinalState.Content->LazyColumn{items(x.value){p->GlassCard(Modifier.fillMaxWidth().padding(vertical=4.dp)){Text(p.name);Text("${p.type} • SKU ${p.sku.orEmpty()}");GlassButton("جزئیات",{nav.navigate("product/${p.id.value}")})}}}}}}}
@Composable private fun ProductDetail(d:V1PresentationDependencies,s:StoreId,id:EntityId,nav:NavHostController){val vm=finalVm{FinalProductVm(d)};val state by vm.state.collectAsState();LaunchedEffect(s,id){vm.load(s,id)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("محصول پیدا نشد");is FinalState.Error->GlassErrorState(x.message){vm.load(s,id)};is FinalState.Content->{GlassTopBar(x.value.name);GlassCard{Text("نوع: ${x.value.type}");Text("SKU: ${x.value.sku.orEmpty()}");Text("قیمت: ${x.value.pricing.regular.orEmpty()}");Text("موجودی: ${x.value.stock?.quantity?.toString().orEmpty()}")};if(x.value.images.isEmpty())GlassEmptyState("گالری خالی است") else LazyColumn{items(x.value.images){i->GlassCard{Text(i.name.orEmpty());Text(i.src);Text("Alt: ${i.alt.orEmpty()}")}}};GlassButton("ویرایش",{nav.navigate("product-edit/${x.value.id.value}")},Modifier.fillMaxWidth());if(x.value.type==ProductType.VARIABLE)GlassButton("Variations",{nav.navigate("variations/${x.value.id.value}")},Modifier.fillMaxWidth());GlassOutlinedButton("حذف",{vm.delete(s,x.value.id){nav.popBackStack()}},Modifier.fillMaxWidth())}}}}}
@Composable private fun ProductEdit(d:V1PresentationDependencies,s:StoreId,id:String,nav:NavHostController){val vm=finalVm{FinalProductVm(d)};var loaded by remember{mutableStateOf<Product?>(null)};var error by remember{mutableStateOf<String?>(null)};if(id!="new")LaunchedEffect(id){when(val r=d.getProduct(s,EntityId(id))){is CoreResult.Success->loaded=r.value;is CoreResult.Failure->error=r.error.toString()}};var name by rememberSaveable{idKey(id){mutableStateOf("")}};var sku by rememberSaveable{idKey(id){mutableStateOf("")}};var regular by rememberSaveable{idKey(id){mutableStateOf("")}};var sale by rememberSaveable{idKey(id){mutableStateOf("")}};var type by rememberSaveable{idKey(id){mutableStateOf(ProductType.SIMPLE)}};LaunchedEffect(loaded){loaded?.let{name=it.name;sku=it.sku.orEmpty();regular=it.pricing.regular.orEmpty();sale=it.pricing.sale.orEmpty();type=it.type}};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){GlassTopBar(if(id=="new")"افزودن محصول" else "ویرایش محصول");error?.let{GlassErrorState(it)};GlassTextField(name,{name=it},"نام محصول");GlassTextField(sku,{sku=it},"SKU");GlassTextField(regular,{regular=it},"قیمت عادی");GlassTextField(sale,{sale=it},"قیمت فروش ویژه");GlassChip("نوع: ${type.name}");GlassButton("ذخیره",{val p=Product(loaded?.id?:localId("product"),name,sku,null,null,loaded?.status?:ProductStatus.DRAFT,type,Pricing(regular.ifBlank{null},sale.ifBlank{null},sale.isNotBlank()),loaded?.stock,loaded?.images?:emptyList(),loaded?.categories?:emptyList(),loaded?.attributes?:emptyList(),loaded?.modifiedAt);if(id=="new")vm.create(s,p){nav.popBackStack()}else vm.save(s,p){nav.popBackStack()}},Modifier.fillMaxWidth(),name.isNotBlank())}}}
private fun <T> idKey(id:String)=object:androidx.compose.runtime.saveable.Saver<T,T>{override fun save(value:T)=value;override fun restore(value:T)=value}
@Composable private fun Variations(d:V1PresentationDependencies,s:StoreId,p:EntityId){val vm=finalVm{FinalVariationVm(d)};val state by vm.state.collectAsState();LaunchedEffect(s,p){vm.load(s,p)};GlassScaffold{pad->Column(Modifier.padding(pad).padding(16.dp)){GlassTopBar("Variations");when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("Variation وجود ندارد");is FinalState.Error->GlassErrorState(x.message){vm.load(s,p)};is FinalState.Content->LazyColumn{items(x.value){v->GlassCard{Text("SKU: ${v.sku.orEmpty()}");Text(v.attributes.joinToString(" • "){"${it.name}: ${it.option}"});Text("قیمت: ${v.pricing.regular.orEmpty()}")}}}}}}}
@Composable private fun Attributes(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=finalVm{FinalAttributeVm(d)};val state by vm.state.collectAsState();var name by rememberSaveable{mutableStateOf("")};LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("ویژگی‌ها");GlassTextField(name,{name=it},"نام ویژگی");GlassButton("افزودن",{vm.add(s,name);name=""},Modifier.fillMaxWidth(),name.isNotBlank());when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("ویژگی وجود ندارد");is FinalState.Error->GlassErrorState(x.message){vm.load(s)};is FinalState.Content->LazyColumn{items(x.value){a->GlassCard{Text(a.name);Text(a.slug);GlassButton("Terms",{nav.navigate("terms/${a.id.value}")})}}}}}}}
@Composable private fun Terms(d:V1PresentationDependencies,s:StoreId,a:EntityId){val vm=finalVm{FinalTermVm(d)};val state by vm.state.collectAsState();var name by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,a){vm.load(s,a)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("Terms");GlassTextField(name,{name=it},"نام Term");GlassButton("افزودن",{vm.add(s,a,name);name=""},Modifier.fillMaxWidth(),name.isNotBlank());when(val x=state){FinalState.Loading->GlassSyncIndicator("در حال دریافت…");FinalState.Empty->GlassEmptyState("Term وجود ندارد");is FinalState.Error->GlassErrorState(x.message){vm.load(s,a)};is FinalState.Content->LazyColumn{items(x.value){t->GlassCard{Text(t.name);Text(t.slug.orEmpty())}}}}}}}
@Composable private fun Sync(d:V1PresentationDependencies,s:StoreId){val vm=finalVm{SyncViewModel(d)};val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){GlassTopBar("همگام‌سازی");when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت…");FeatureUiState.Empty->GlassEmptyState("وضعیت موجود نیست");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s)};is FeatureUiState.Success->GlassCard{Text("State: ${x.value.state}")}};GlassButton("همگام‌سازی الآن",{vm.sync(s)},Modifier.fillMaxWidth())}}}
@Composable private fun Conflicts(d:V1PresentationDependencies,s:StoreId){val vm=finalVm{ConflictsViewModel(d)};val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("تعارض‌ها");when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت…");FeatureUiState.Empty->GlassEmptyState("تعارضی وجود ندارد");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s)};is FeatureUiState.Success->LazyColumn{items(x.value){c->GlassCard{Text("${c.entityType} / ${c.entityId.value}");Text("Local: ${c.localSnapshot}");Text("Server: ${c.serverSnapshot}");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){GlassButton("محلی",{vm.resolve(s,c.id,ConflictResolution.KEEP_LOCAL)});GlassOutlinedButton("سرور",{vm.resolve(s,c.id,ConflictResolution.KEEP_SERVER)})}}}}}}}}}
@Composable private fun Settings(d:V1PresentationDependencies,s:StoreId,nav:NavHostController,off:()->Unit){GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){GlassTopBar("تنظیمات");GlassCard{Text("Store ID");Text(s.value)};GlassButton("Sync",{nav.navigate("sync")},Modifier.fillMaxWidth());GlassOutlinedButton("قطع اتصال امن",{d.onStoreDisconnected();off();nav.navigate("connect"){popUpTo("settings"){inclusive=true}}},Modifier.fillMaxWidth())}}}
