package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.*
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.core.domain.usecase.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

private sealed interface E11State<out T> { data object Loading:E11State<Nothing>; data object Empty:E11State<Nothing>; data class Content<T>(val value:T):E11State<T>; data class Error(val message:String):E11State<Nothing>; data object Offline:E11State<Nothing> }
private fun <T:ViewModel> e11Vm(factory:()->T)=viewModel<T>(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <M:ViewModel> create(modelClass:Class<M>):M=factory() as M})
private fun newId(prefix:String)=EntityId("local-$prefix-${System.currentTimeMillis()}")

class E11OrdersVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<List<Order>>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId,q:String?=null){viewModelScope.launch{_state.value=E11State.Loading;_state.value=when(val r=d.getOrders(s,1,30,q,null)){is CoreResult.Success->if(r.value.isEmpty())E11State.Empty else E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}}}
class E11ProductsVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<List<Product>>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId,q:String?=null){viewModelScope.launch{_state.value=E11State.Loading;_state.value=when(val r=d.getProducts(s,1,30,q)){is CoreResult.Success->if(r.value.isEmpty())E11State.Empty else E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}}}
class E11ProductVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<Product>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId,id:EntityId){viewModelScope.launch{_state.value=when(val r=d.getProduct(s,id)){is CoreResult.Success->E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}};fun save(s:StoreId,p:Product){viewModelScope.launch{_state.value=when(val r=d.updateProduct(s,p.id,p)){is CoreResult.Success->E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}};fun delete(s:StoreId,id:EntityId,onDone:()->Unit){viewModelScope.launch{when(d.deleteProduct(s,id)){is CoreResult.Success->onDone();is CoreResult.Failure->Unit}}}}
class E11VariationVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<List<Variation>>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId,p:EntityId){viewModelScope.launch{_state.value=when(val r=d.getVariations(s,p,1,30)){is CoreResult.Success->if(r.value.isEmpty())E11State.Empty else E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}}}
class E11AttributeVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<List<GlobalAttribute>>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId){viewModelScope.launch{_state.value=when(val r=d.getAttributes(s,1,100)){is CoreResult.Success->if(r.value.isEmpty())E11State.Empty else E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}};fun create(s:StoreId,name:String){viewModelScope.launch{d.createAttribute(s,GlobalAttribute(newId("attribute"),name,name.lowercase().replace(" ","-"),emptyList()));load(s)}}}
class E11TermVm(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<E11State<List<AttributeTerm>>>(E11State.Loading);val state=_state.asStateFlow();fun load(s:StoreId,a:EntityId){viewModelScope.launch{_state.value=when(val r=d.getTerms(s,a,1,100)){is CoreResult.Success->if(r.value.isEmpty())E11State.Empty else E11State.Content(r.value);is CoreResult.Failure->E11State.Error(r.error.toString())}}};fun create(s:StoreId,a:EntityId,name:String){viewModelScope.launch{d.createTerm(s,a,AttributeTerm(null,name,name.lowercase().replace(" ","-")));load(s,a)}}}

@Composable fun E11WooGitApp(d:V1PresentationDependencies){var active by rememberSaveable{mutableStateOf(d.initialStoreId)};val nav=rememberNavController();NavHost(nav,if(active==null)"connect" else "dashboard"){composable("connect"){E11Connect(d){id->active=id;nav.navigate("dashboard"){popUpTo("connect"){inclusive=true}}}};composable("dashboard"){E11Dashboard(d,StoreId(active!!),nav)};composable("orders"){E11Orders(d,StoreId(active!!),nav)};composable("order/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){E11OrderDetail(d,StoreId(active!!),EntityId(it.arguments!!.getString("id")!!),nav)};composable("products"){E11Products(d,StoreId(active!!),nav)};composable("product/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){E11ProductDetail(d,StoreId(active!!),EntityId(it.arguments!!.getString("id")!!),nav)};composable("variations/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){E11Variations(d,StoreId(active!!),EntityId(it.arguments!!.getString("id")!!))};composable("attributes"){E11Attributes(d,StoreId(active!!),nav)};composable("terms/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){E11Terms(d,StoreId(active!!),EntityId(it.arguments!!.getString("id")!!))};composable("sync"){E11Sync(d,StoreId(active!!))};composable("conflicts"){E11Conflicts(d,StoreId(active!!))};composable("settings"){E11Settings(d,StoreId(active!!),nav){active=null}}}}

@Composable private fun E11Connect(d:V1PresentationDependencies,done:(String)->Unit){val vm=e11Vm{ConnectionViewModel(d)};val state by vm.state.collectAsState();var url by rememberSaveable{mutableStateOf("")};var key by rememberSaveable{mutableStateOf("")};var secret by rememberSaveable{mutableStateOf("")};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){GlassTopBar("اتصال فروشگاه","WooCommerce");GlassTextField(url,{url=it},"Store URL");GlassTextField(key,{key=it},"Consumer Key");GlassTextField(secret,{secret=it},"Consumer Secret",secret=true);when(state){is FeatureUiState.Error->GlassErrorState((state as FeatureUiState.Error).message);else->Unit};GlassButton("اتصال و بررسی",{vm.connect(url,key,secret)},Modifier.fillMaxWidth(),url.isNotBlank()&&key.isNotBlank()&&secret.isNotBlank());if(state is FeatureUiState.Success){done((state as FeatureUiState.Success<StoreConnection>).value.storeId.value)}}}}

@Composable private fun E11Dashboard(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val sync=remember{d.getSyncState};var syncText by remember{mutableStateOf("در حال بررسی…")};LaunchedEffect(s){syncText=when(val r=d.getSyncState(s)){is CoreResult.Success->r.value.state.toString();is CoreResult.Failure->"نامشخص"}};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){GlassTopBar("داشبورد","Store: ${s.value}");GlassCard{Text("وضعیت همگام‌سازی");Text(syncText)};GlassButton("سفارش‌ها",{nav.navigate("orders")},Modifier.fillMaxWidth());GlassButton("محصولات",{nav.navigate("products")},Modifier.fillMaxWidth());GlassButton("ویژگی‌ها",{nav.navigate("attributes")},Modifier.fillMaxWidth());GlassButton("همگام‌سازی",{nav.navigate("sync")},Modifier.fillMaxWidth());GlassButton("تعارض‌ها",{nav.navigate("conflicts")},Modifier.fillMaxWidth());GlassOutlinedButton("تنظیمات",{nav.navigate("settings")},Modifier.fillMaxWidth())}}}

@Composable private fun E11Orders(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=e11Vm{E11OrdersVm(d)};val state by vm.state.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.load(s,q.ifBlank{null})};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("سفارش‌ها");GlassSearchField(q,{q=it},"جستجو");when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت…");E11State.Empty->GlassEmptyState("سفارشی وجود ندارد", "داده محلی یا نتیجه جستجو خالی است");is E11State.Error->GlassErrorState(x.message){vm.load(s,q.ifBlank{null})};is E11State.Content->LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(x.value){o->GlassCard(Modifier.fillMaxWidth()){Text("#${o.number}",style=MaterialTheme.typography.titleMedium);Text("${o.status} • ${o.total.orEmpty()} ${o.currency.orEmpty()}");GlassButton("جزئیات",{nav.navigate("order/${o.id.value}")})}}};E11State.Offline->GlassEmptyState("آفلاین")}}}}

@Composable private fun E11OrderDetail(d:V1PresentationDependencies,s:StoreId,id:EntityId,nav:NavHostController){val vm=e11Vm{OrderDetailViewModel(d)};val state by vm.state.collectAsState();var note by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,id){vm.load(s,id)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت سفارش…");FeatureUiState.Empty->GlassEmptyState("سفارش پیدا نشد");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s,id)};is FeatureUiState.Success->{GlassTopBar("سفارش #${x.value.number}");GlassCard{Text("وضعیت: ${x.value.status}");Text("مبلغ: ${x.value.total.orEmpty()} ${x.value.currency.orEmpty()}");Text("پرداخت: ${x.value.payment?.methodTitle.orEmpty()}");Text("اقلام: ${x.value.items.size}")};GlassTextField(note,{note=it},"یادداشت");GlassButton("افزودن یادداشت",{vm.note(s,id,note);note=""},Modifier.fillMaxWidth(),note.isNotBlank());GlassButton("تغییر به Processing",{vm.update(s,x.value.copy(status=OrderStatus.PROCESSING))},Modifier.fillMaxWidth())}}}}}

@Composable private fun E11Products(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=e11Vm{E11ProductsVm(d)};val state by vm.state.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.load(s,q.ifBlank{null})};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("محصولات");GlassSearchField(q,{q=it},"جستجو");GlassButton("افزودن سریع محصول",{nav.navigate("product/new")},Modifier.fillMaxWidth());when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت…");E11State.Empty->GlassEmptyState("محصولی وجود ندارد");is E11State.Error->GlassErrorState(x.message){vm.load(s,q.ifBlank{null})};is E11State.Content->LazyColumn{items(x.value){p->GlassCard(Modifier.fillMaxWidth().padding(vertical=4.dp)){Text(p.name,style=MaterialTheme.typography.titleMedium);Text("${p.type} • SKU ${p.sku.orEmpty()}");GlassButton("ویرایش",{nav.navigate("product/${p.id.value}")})}}};E11State.Offline->GlassEmptyState("آفلاین")}}}}}

@Composable private fun E11ProductDetail(d:V1PresentationDependencies,s:StoreId,id:EntityId,nav:NavHostController){if(id.value=="new"){E11ProductEditor(d,s,nav,null);return};val vm=e11Vm{E11ProductVm(d)};val state by vm.state.collectAsState();LaunchedEffect(s,id){vm.load(s,id)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت محصول…");E11State.Empty->GlassEmptyState("محصول پیدا نشد");is E11State.Error->GlassErrorState(x.message){vm.load(s,id)};is E11State.Content->{GlassTopBar(x.value.name);GlassCard{Text("نوع: ${x.value.type}");Text("SKU: ${x.value.sku.orEmpty()}");Text("قیمت: ${x.value.pricing.regular.orEmpty()}");Text("موجودی: ${x.value.stock?.quantity?.toString().orEmpty()}")};if(x.value.images.isEmpty())GlassEmptyState("تصویری وجود ندارد","تصویر اصلی و گالری در این نسخه از داده محلی/ووکامرس نمایش داده می‌شوند")else LazyColumn{items(x.value.images){img->GlassCard{Text(img.name.orEmpty());Text(img.src);Text("Alt: ${img.alt.orEmpty()}")}}};GlassButton("ویرایش",{nav.navigate("product/${x.value.id.value}/edit")},Modifier.fillMaxWidth());if(x.value.type==ProductType.VARIABLE)GlassButton("مدیریت Variations",{nav.navigate("variations/${x.value.id.value}")},Modifier.fillMaxWidth());GlassOutlinedButton("حذف محصول",{vm.delete(s,x.value.id){nav.popBackStack()}},Modifier.fillMaxWidth())}}}}}

@Composable private fun E11ProductEditor(d:V1PresentationDependencies,s:StoreId,nav:NavHostController,initial:Product?){var name by rememberSaveable{mutableStateOf(initial?.name.orEmpty())};var sku by rememberSaveable{mutableStateOf(initial?.sku.orEmpty())};var regular by rememberSaveable{mutableStateOf(initial?.pricing?.regular.orEmpty())};var sale by rememberSaveable{mutableStateOf(initial?.pricing?.sale.orEmpty())};var type by rememberSaveable{mutableStateOf(initial?.type?.name?:ProductType.SIMPLE.name)};var busy by remember{mutableStateOf(false)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){GlassTopBar(if(initial==null)"افزودن محصول" else "ویرایش محصول");GlassTextField(name,{name=it},"نام محصول");GlassTextField(sku,{sku=it},"SKU");GlassTextField(regular,{regular=it},"قیمت عادی");GlassTextField(sale,{sale=it},"قیمت فروش ویژه");GlassChip("نوع: $type");GlassButton(if(initial==null)"ایجاد محصول" else "ذخیره تغییرات",{busy=true;val product=Product(initial?.id?:newId("product"),name,sku,null,null,initial?.status?:ProductStatus.DRAFT,ProductType.valueOf(type),Pricing(regular.ifBlank{null},sale.ifBlank{null},!sale.isNullOrBlank()),initial?.stock,initial?.images?:emptyList(),initial?.categories?:emptyList(),initial?.attributes?:emptyList(),initial?.modifiedAt);LaunchedEffect(Unit){val r=if(initial==null)d.createProduct(s,product)else d.updateProduct(s,product.id,product);busy=false;if(r is CoreResult.Success)nav.popBackStack()}},Modifier.fillMaxWidth(),!busy&&name.isNotBlank())}}}

@Composable private fun E11Variations(d:V1PresentationDependencies,s:StoreId,p:EntityId){val vm=e11Vm{E11VariationVm(d)};val state by vm.state.collectAsState();LaunchedEffect(s,p){vm.load(s,p)};GlassScaffold{pad->Column(Modifier.padding(pad).padding(16.dp)){GlassTopBar("Variations");when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت…");E11State.Empty->GlassEmptyState("Variation وجود ندارد");is E11State.Error->GlassErrorState(x.message){vm.load(s,p)};is E11State.Content->LazyColumn{items(x.value){v->GlassCard{Text("SKU: ${v.sku.orEmpty()}");Text(v.attributes.joinToString(" • "){"${it.name}: ${it.option}"});Text("قیمت: ${v.pricing.regular.orEmpty()}")}}};E11State.Offline->GlassEmptyState("آفلاین")}}}}}

@Composable private fun E11Attributes(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm=e11Vm{E11AttributeVm(d)};val state by vm.state.collectAsState();var name by rememberSaveable{mutableStateOf("")};LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("ویژگی‌های سراسری");GlassTextField(name,{name=it},"نام ویژگی");GlassButton("افزودن ویژگی",{vm.create(s,name);name=""},Modifier.fillMaxWidth(),name.isNotBlank());when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت…");E11State.Empty->GlassEmptyState("ویژگی وجود ندارد");is E11State.Error->GlassErrorState(x.message){vm.load(s)};is E11State.Content->LazyColumn{items(x.value){a->GlassCard{Text(a.name);Text(a.slug);GlassButton("Terms",{nav.navigate("terms/${a.id.value}")})}}};E11State.Offline->GlassEmptyState("آفلاین")}}}}}

@Composable private fun E11Terms(d:V1PresentationDependencies,s:StoreId,a:EntityId){val vm=e11Vm{E11TermVm(d)};val state by vm.state.collectAsState();var name by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,a){vm.load(s,a)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("Terms");GlassTextField(name,{name=it},"نام Term");GlassButton("افزودن Term",{vm.create(s,a,name);name=""},Modifier.fillMaxWidth(),name.isNotBlank());when(val x=state){E11State.Loading->GlassSyncIndicator("در حال دریافت…");E11State.Empty->GlassEmptyState("Term وجود ندارد");is E11State.Error->GlassErrorState(x.message){vm.load(s,a)};is E11State.Content->LazyColumn{items(x.value){t->GlassCard{Text(t.name);Text(t.slug.orEmpty())}}};E11State.Offline->GlassEmptyState("آفلاین")}}}}}

@Composable private fun E11Sync(d:V1PresentationDependencies,s:StoreId){val vm=e11Vm{SyncViewModel(d)};val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){GlassTopBar("Sync");when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت وضعیت…");FeatureUiState.Empty->GlassEmptyState("وضعیت موجود نیست");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s)};is FeatureUiState.Success->GlassCard{Text("State: ${x.value.state}")}};GlassButton("همگام‌سازی الآن",{vm.sync(s)},Modifier.fillMaxWidth())}}}

@Composable private fun E11Conflicts(d:V1PresentationDependencies,s:StoreId){val vm=e11Vm{ConflictsViewModel(d)};val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};GlassScaffold{p->Column(Modifier.padding(p).padding(16.dp)){GlassTopBar("تعارض‌ها");when(val x=state){FeatureUiState.Loading->GlassSyncIndicator("در حال دریافت…");FeatureUiState.Empty->GlassEmptyState("تعارضی وجود ندارد");is FeatureUiState.Error->GlassErrorState(x.message){vm.load(s)};is FeatureUiState.Success->LazyColumn{items(x.value){c->GlassCard{Text("${c.entityType} / ${c.entityId.value}");Text("Local: ${c.localSnapshot}");Text("Server: ${c.serverSnapshot}");Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){GlassButton("نگه‌داشتن محلی",{vm.resolve(s,c.id,ConflictResolution.KEEP_LOCAL)});GlassOutlinedButton("نگه‌داشتن سرور",{vm.resolve(s,c.id,ConflictResolution.KEEP_SERVER)})}}}}}}}}}

@Composable private fun E11Settings(d:V1PresentationDependencies,s:StoreId,nav:NavHostController,onDisconnect:()->Unit){GlassScaffold{p->Column(Modifier.padding(p).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){GlassTopBar("تنظیمات");GlassCard{Text("Store ID");Text(s.value)};GlassButton("مدیریت Sync",{nav.navigate("sync")},Modifier.fillMaxWidth());GlassOutlinedButton("قطع اتصال امن",{d.onStoreDisconnected();onDisconnect();nav.navigate("connect"){popUpTo("settings"){inclusive=true}}},Modifier.fillMaxWidth())}}}
