package com.samanramezani1377.woogit.presentation

import android.text.Html
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.shadow
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage

object GlassTokens { val radiusSm=16.dp; val radiusMd=24.dp; val radiusLg=32.dp; val spacingXs=4.dp; val spacingSm=8.dp; val spacingMd=12.dp; val spacingLg=20.dp; val spacingXl=28.dp; val glassBorder=Color.White.copy(alpha=.34f) }
private fun String.glassLabel(): String = when (lowercase()) { "published"->"منتشر شده";"draft"->"پیش‌نویس";"pending"->"در انتظار";"private"->"خصوصی";"other"->"سایر";"in_stock"->"موجود";"out_of_stock"->"ناموجود";"on_backorder"->"پیش‌سفارش";"simple"->"ساده";"grouped"->"گروهی";"external"->"خارجی";"variable"->"متغیر";"processing"->"در حال پردازش";"on_hold"->"در انتظار";"completed"->"تکمیل شده";"cancelled"->"لغو شده";"refunded"->"مسترد شده";"failed"->"ناموفق";"connected"->"متصل";"offline"->"آفلاین";"conflict"->"تعارض";else->this }
private fun String.stripHtml(): String = Html.fromHtml(this,Html.FROM_HTML_MODE_LEGACY).toString()
private fun String.toWooHtml(): String = replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\r\n","\n").replace("\r","\n").split("\n").joinToString("<br />")
@Composable fun GlassScaffold(modifier:Modifier=Modifier,content:@Composable(PaddingValues)->Unit){Box(modifier.fillMaxSize().background(Brush.verticalGradient(listOf(Color(0xFFEFF5FF),Color(0xFFDCE7F7),Color(0xFFF7F9FC))))){Box(Modifier.fillMaxSize().padding(18.dp).background(Brush.radialGradient(listOf(Color.White.copy(.30f),Color.Transparent),radius=900f)));Scaffold(modifier=Modifier.fillMaxSize(),containerColor=Color.Transparent,contentWindowInsets=WindowInsets.safeDrawing,content=content)}}
@Composable fun GlassTopBar(title:String,subtitle:String?=null,modifier:Modifier=Modifier,navigation:(@Composable()->Unit)?=null,actions:(@Composable RowScope.()->Unit)?=null){Surface(modifier.fillMaxWidth().padding(bottom=8.dp),shape=RoundedCornerShape(GlassTokens.radiusMd),color=Color.White.copy(.38f),border=BorderStroke(1.dp,GlassTokens.glassBorder),shadowElevation=8.dp){Row(Modifier.fillMaxWidth().padding(16.dp),verticalAlignment=Alignment.CenterVertically){navigation?.invoke();Column(Modifier.weight(1f)){Text(title,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.SemiBold);if(!subtitle.isNullOrBlank())Text(subtitle.glassLabel(),style=MaterialTheme.typography.bodyMedium,color=MaterialTheme.colorScheme.onSurfaceVariant)};actions?.let{Row(horizontalArrangement=Arrangement.spacedBy(4.dp),content=it)}}}}
@Composable fun GlassText(text:String,modifier:Modifier=Modifier,style:androidx.compose.ui.text.TextStyle=MaterialTheme.typography.bodyLarge)=Text(text.stripHtml(),modifier,style)
@Composable fun GlassCard(modifier:Modifier=Modifier,content:@Composable ColumnScope.()->Unit){Surface(modifier.fillMaxWidth().shadow(12.dp,RoundedCornerShape(GlassTokens.radiusMd)),shape=RoundedCornerShape(GlassTokens.radiusMd),color=Color.White.copy(.48f),border=BorderStroke(1.dp,GlassTokens.glassBorder)){Column(Modifier.padding(GlassTokens.spacingLg),verticalArrangement=Arrangement.spacedBy(8.dp),content=content)}}
@Composable fun GlassSection(title:String,modifier:Modifier=Modifier,content:@Composable ColumnScope.()->Unit){Column(modifier.fillMaxWidth(),verticalArrangement=Arrangement.spacedBy(8.dp)){Text(title,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.SemiBold);content()}}
@Composable fun GlassDivider(modifier:Modifier=Modifier)=HorizontalDivider(modifier,color=Color.White.copy(.45f))
@Composable fun GlassButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=Button(onClick,modifier.heightIn(min=50.dp),enabled,shape=RoundedCornerShape(GlassTokens.radiusSm),colors=ButtonDefaults.buttonColors(containerColor=Color.White.copy(.58f),contentColor=MaterialTheme.colorScheme.onSurface),elevation=ButtonDefaults.buttonElevation(defaultElevation=4.dp,pressedElevation=1.dp)){Text(label.glassLabel())}
@Composable fun GlassSecondaryButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=FilledTonalButton(onClick,modifier.heightIn(min=50.dp),enabled,shape=RoundedCornerShape(GlassTokens.radiusSm)){Text(label.glassLabel())}
@Composable fun GlassOutlinedButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=OutlinedButton(onClick,modifier.heightIn(min=50.dp),enabled,shape=RoundedCornerShape(GlassTokens.radiusSm),border=BorderStroke(1.dp,GlassTokens.glassBorder)){Text(label.glassLabel())}
@Composable fun GlassTextButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=TextButton(onClick,modifier.heightIn(min=44.dp),enabled){Text(label.glassLabel())}
@Composable fun GlassIconButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=IconButton(onClick,modifier.sizeIn(minWidth=48.dp,minHeight=48.dp),enabled){Text(label,Modifier.semantics{contentDescription=label;role=Role.Button})}
@Composable fun GlassFloatingActionButton(label:String,onClick:()->Unit,modifier:Modifier=Modifier)=FloatingActionButton(onClick,modifier.sizeIn(minWidth=48.dp,minHeight=48.dp),shape=RoundedCornerShape(GlassTokens.radiusMd)){Text(label)}
@Composable fun GlassTextField(value:String,onValueChange:(String)->Unit,label:String,modifier:Modifier=Modifier,enabled:Boolean=true,singleLine:Boolean=true){val rich=label=="توضیحات"||label=="توضیح کوتاه";val display=if(rich)value.stripHtml() else value;OutlinedTextField(display,{onValueChange(if(rich)it.toWooHtml() else it)},modifier.fillMaxWidth(),enabled,singleLine=singleLine,label={Text(label)},shape=RoundedCornerShape(GlassTokens.radiusSm),colors=OutlinedTextFieldDefaults.colors(unfocusedContainerColor=Color.White.copy(.25f),focusedContainerColor=Color.White.copy(.38f),unfocusedBorderColor=GlassTokens.glassBorder,focusedBorderColor=MaterialTheme.colorScheme.primary))}
@Composable fun GlassPasswordField(value:String,onValueChange:(String)->Unit,label:String="Consumer Secret",modifier:Modifier=Modifier,enabled:Boolean=true)=OutlinedTextField(value,onValueChange,modifier.fillMaxWidth(),enabled,singleLine=true,label={Text(label)},visualTransformation=PasswordVisualTransformation(),shape=RoundedCornerShape(GlassTokens.radiusSm))
@Composable fun GlassSearchField(value:String,onValueChange:(String)->Unit,label:String="جستجو",modifier:Modifier=Modifier,onClear:(()->Unit)?=null)=OutlinedTextField(value,onValueChange,modifier.fillMaxWidth(),singleLine=true,label={Text(label)},trailingIcon={if(value.isNotEmpty())GlassTextButton("پاک",{onClear?.invoke()?:onValueChange("")})},shape=RoundedCornerShape(GlassTokens.radiusSm))
@Composable fun <T> GlassDropdown(label:String,selected:T,options:List<T>,optionLabel:(T)->String,onSelected:(T)->Unit,modifier:Modifier=Modifier,enabled:Boolean=true){var expanded by remember{mutableStateOf(false)};Box(modifier.fillMaxWidth()){GlassOutlinedButton(optionLabel(selected).glassLabel(),{expanded=true},Modifier.fillMaxWidth(),enabled);DropdownMenu(expanded,onDismissRequest={expanded=false}){options.forEach{option->DropdownMenuItem(text={Text(optionLabel(option).glassLabel())},onClick={expanded=false;onSelected(option)})}}}}
@Composable fun GlassCheckbox(checked:Boolean,onCheckedChange:(Boolean)->Unit,label:String,modifier:Modifier=Modifier)=Row(modifier.fillMaxWidth().heightIn(min=48.dp),verticalAlignment=Alignment.CenterVertically){Checkbox(checked,onCheckedChange);Text(label)}
@Composable fun GlassSwitch(checked:Boolean,onCheckedChange:(Boolean)->Unit,label:String,modifier:Modifier=Modifier)=Row(modifier.fillMaxWidth().heightIn(min=48.dp),verticalAlignment=Alignment.CenterVertically){Text(label,Modifier.weight(1f));Switch(checked,onCheckedChange)}
@Composable fun GlassRadioButton(selected:Boolean,onClick:()->Unit,label:String,modifier:Modifier=Modifier)=Row(modifier.fillMaxWidth().heightIn(min=48.dp),verticalAlignment=Alignment.CenterVertically){RadioButton(selected,onClick);Text(label)}
@Composable fun GlassChip(label:String,modifier:Modifier=Modifier)=AssistChip(onClick={},label={Text(label.glassLabel())},modifier=modifier.heightIn(min=40.dp))
@Composable fun GlassStatusBadge(label:String,modifier:Modifier=Modifier)=Surface(modifier,shape=RoundedCornerShape(50),color=Color.White.copy(.52f),border=BorderStroke(1.dp,GlassTokens.glassBorder)){Text(label.glassLabel(),Modifier.padding(horizontal=12.dp,vertical=7.dp),style=MaterialTheme.typography.labelMedium)}
@Composable fun GlassListItem(title:String,subtitle:String?=null,modifier:Modifier=Modifier,onClick:(()->Unit)?=null,trailing:(@Composable()->Unit)?=null){val body:@Composable()->Unit={Row(Modifier.fillMaxWidth().padding(horizontal=14.dp,vertical=12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title.stripHtml(),style=MaterialTheme.typography.titleSmall);if(!subtitle.isNullOrBlank())Text(subtitle.stripHtml(),style=MaterialTheme.typography.bodySmall,color=MaterialTheme.colorScheme.onSurfaceVariant)};trailing?.invoke()}};Surface(modifier.fillMaxWidth().heightIn(min=68.dp),shape=RoundedCornerShape(GlassTokens.radiusSm),color=Color.White.copy(.40f),border=BorderStroke(1.dp,GlassTokens.glassBorder),onClick=onClick?:{}){body()}}
@Composable fun GlassPrimaryAction(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=GlassButton(label,onClick,modifier,enabled)
@Composable fun GlassDestructiveAction(label:String,onClick:()->Unit,modifier:Modifier=Modifier,enabled:Boolean=true)=GlassOutlinedButton(label,onClick,modifier,enabled)
@Composable fun GlassLoading(label:String="در حال بارگذاری…")=Column(Modifier.fillMaxWidth().padding(GlassTokens.spacingXl),horizontalAlignment=Alignment.CenterHorizontally,verticalArrangement=Arrangement.spacedBy(GlassTokens.spacingSm)){CircularProgressIndicator();Text(label)}
@Composable fun GlassSyncIndicator(label:String="در حال همگام‌سازی…")=GlassStatusBadge(label)
@Composable fun GlassEmptyState(message:String,actionLabel:String?=null,onAction:(()->Unit)?=null)=GlassCard{Text(message);if(actionLabel!=null&&onAction!=null)GlassButton(actionLabel,onAction,Modifier.fillMaxWidth())}
@Composable fun GlassErrorState(message:String,retry:(()->Unit)?=null)=GlassCard{Text(message,color=MaterialTheme.colorScheme.error);if(retry!=null)GlassButton("تلاش دوباره",retry,Modifier.fillMaxWidth())}
@Composable fun GlassOfflineState(message:String="آفلاین هستید؛ داده‌های ذخیره‌شده نمایش داده می‌شوند.")=GlassCard{GlassStatusBadge("آفلاین");Text(message)}
@Composable fun GlassPendingState(count:Int=0)=GlassCard{GlassStatusBadge("در انتظار${if(count>0)" • $count" else ""}");Text("تغییرات محلی منتظر همگام‌سازی هستند.")}
@Composable fun GlassConflictState(message:String="برای ادامه باید تعارض را بررسی کنید.")=GlassCard{GlassStatusBadge("تعارض");Text(message)}
@Composable fun GlassDialog(show:Boolean,title:String,onDismiss:()->Unit,confirmLabel:String="تأیید",onConfirm:()->Unit,content:@Composable ColumnScope.()->Unit){if(show)AlertDialog(onDismissRequest=onDismiss,title={Text(title)},text={Column(content=content)},confirmButton={TextButton(onClick=onConfirm){Text(confirmLabel)}},dismissButton={TextButton(onClick=onDismiss){Text("انصراف")}})}
@OptIn(ExperimentalMaterial3Api::class) @Composable fun GlassBottomSheet(show:Boolean,onDismiss:()->Unit,content:@Composable ColumnScope.()->Unit){if(show)ModalBottomSheet(onDismissRequest=onDismiss){Column(Modifier.padding(20.dp),content=content)}}
@Composable fun GlassSnackbar(hostState:SnackbarHostState,modifier:Modifier=Modifier)=SnackbarHost(hostState,modifier)
@Composable fun GlassImage(src:String,contentDescription:String?,modifier:Modifier=Modifier)=AsyncImage(model=src,contentDescription=contentDescription,modifier=modifier.fillMaxWidth())
@Composable fun GlassListState(state:FeatureUiState<*>,emptyMessage:String,errorRetry:(()->Unit)?=null,content:@Composable()->Unit){when(state){FeatureUiState.Loading->GlassLoading();FeatureUiState.Empty->GlassEmptyState(emptyMessage);is FeatureUiState.Error->GlassErrorState(state.message,errorRetry);FeatureUiState.Offline->GlassOfflineState();FeatureUiState.Pending->GlassPendingState();is FeatureUiState.Conflict->GlassConflictState();is FeatureUiState.Success<*>->content()}}
