package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.core.domain.usecase.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class V1PresentationDependencies(
 val getStore:GetStore,val connectStore:ConnectStore,val disconnectStore:DisconnectStore,val getOrders:GetOrders,val getOrder:GetOrder,val updateOrder:UpdateOrder,val addOrderNote:AddOrderNote,
 val getProducts:GetProducts,val getProduct:GetProduct,val createProduct:CreateProduct,val updateProduct:UpdateProduct,val deleteProduct:DeleteProduct,
 val getVariations:GetVariations,val getVariation:GetVariation,val createVariation:CreateVariation,val updateVariation:UpdateVariation,val deleteVariation:DeleteVariation,
 val getAttributes:GetAttributes,val getAttribute:GetAttribute,val createAttribute:CreateAttribute,val updateAttribute:UpdateAttribute,val deleteAttribute:DeleteAttribute,
 val getTerms:GetTerms,val getTerm:GetTerm,val createTerm:CreateTerm,val updateTerm:UpdateTerm,val deleteTerm:DeleteTerm,val getConnectionState:GetConnectionState,val getSyncState:GetSyncState,val getPending:GetPendingOperations,
 val getConflicts:suspend(StoreId)->CoreResult<List<Conflict>>,val resolveConflict:suspend(StoreId,EntityId,ConflictResolution)->CoreResult<Unit>,val syncPending:SyncPendingOperations,val initialStoreId:String?,val onStoreConnected:(String)->Unit,val onStoreDisconnected:()->Unit)

sealed interface FeatureUiState<out T>{data object Loading:FeatureUiState<Nothing>;data object Empty:FeatureUiState<Nothing>;data class Success<T>(val value:T):FeatureUiState<T>;data class Error(val message:String):FeatureUiState<Nothing>}
private fun <T:ViewModel> vmFactory(create:()->T)=object:ViewModelProvider.Factory{override fun <M:ViewModel>create(modelClass:Class<M>):M=create() as M}
private fun storeIdFor(url:String)=StoreId("store-${url.trim().trimEnd('/').lowercase().hashCode().toUInt().toString(16)}")

class ConnectionViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<StoreConnection>>(FeatureUiState.Loading);val state:StateFlow<FeatureUiState<StoreConnection>>=_state.asStateFlow();fun connect(url:String,key:String,secret:String){viewModelScope.launch{_state.value=FeatureUiState.Loading;when(val r=d.connectStore(StoreConnection(storeIdFor(url),url.trim().trimEnd('/'),ConnectionState.DISCONNECTED,null),key,secret)){is CoreResult.Success->{_state.value=FeatureUiState.Success(r.value);d.onStoreConnected(r.value.storeId.value)};is CoreResult.Failure->_state.value=FeatureUiState.Error(r.error.toString())}}}}
class OrdersViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Order>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,page:Int=1,search:String?=null){viewModelScope.launch{_state.value=FeatureUiState.Loading;_state.value=when(val r=d.getOrders(s,page,30,search)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class OrderDetailViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<Order>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,id:EntityId){viewModelScope.launch{_state.value=when(val r=d.getOrder(s,id)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun update(s:StoreId,o:Order){viewModelScope.launch{_state.value=when(val r=d.updateOrder(s,o.id,o)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun note(s:StoreId,id:EntityId,text:String){viewModelScope.launch{d.addOrderNote(s,id,text)}}}
class ProductsViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Product>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,page:Int=1,search:String?=null){viewModelScope.launch{_state.value=FeatureUiState.Loading;_state.value=when(val r=d.getProducts(s,page,30,search)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class ProductDetailViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<Product>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,id:EntityId){viewModelScope.launch{_state.value=when(val r=d.getProduct(s,id)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun save(s:StoreId,p:Product){viewModelScope.launch{_state.value=when(val r=d.updateProduct(s,p.id,p)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class VariationsViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Variation>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,p:EntityId){viewModelScope.launch{_state.value=when(val r=d.getVariations(s,p)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class AttributesViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<GlobalAttribute>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId){viewModelScope.launch{_state.value=when(val r=d.getAttributes(s)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class TermsViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<AttributeTerm>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId,a:EntityId){viewModelScope.launch{_state.value=when(val r=d.getTerms(s,a)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class SyncViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<SyncMetadata>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId){viewModelScope.launch{_state.value=when(val r=d.getSyncState(s)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun sync(s:StoreId){viewModelScope.launch{d.syncPending(s);load(s)}}}
class ConflictsViewModel(private val d:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Conflict>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(s:StoreId){viewModelScope.launch{_state.value=when(val r=d.getConflicts(s)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun resolve(s:StoreId,id:EntityId,r:ConflictResolution){viewModelScope.launch{d.resolveConflict(s,id,r);load(s)}}}

@Composable fun V1WooGitApp(d:V1PresentationDependencies){val nav=rememberNavController();var activeStore by rememberSaveable{mutableStateOf(d.initialStoreId)};NavHost(navController=nav,startDestination=if(activeStore==null)"connection" else "dashboard"){composable("connection"){ConnectionScreen(d){id->activeStore=id;nav.navigate("dashboard"){popUpTo("connection"){inclusive=true}}}};composable("dashboard"){activeStore?.let{Dashboard(nav,StoreId(it))}};composable("orders"){activeStore?.let{OrdersScreen(d,StoreId(it),nav)}};composable("orders/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->activeStore?.let{OrderDetailScreen(d,StoreId(it),EntityId(b.arguments?.getString("id")?:"0"))}};composable("products"){activeStore?.let{ProductsScreen(d,StoreId(it),nav)}};composable("products/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->activeStore?.let{ProductDetailScreen(d,StoreId(it),EntityId(b.arguments?.getString("id")?:"0"),nav)}};composable("variations/{productId}",arguments=listOf(navArgument("productId"){type=NavType.StringType})){b->activeStore?.let{VariationsScreen(d,StoreId(it),EntityId(b.arguments?.getString("productId")?:"0"))}};composable("attributes"){activeStore?.let{AttributesScreen(d,StoreId(it),nav)}};composable("terms/{attributeId}",arguments=listOf(navArgument("attributeId"){type=NavType.StringType})){b->activeStore?.let{TermsScreen(d,StoreId(it),EntityId(b.arguments?.getString("attributeId")?:"0"))}};composable("sync"){activeStore?.let{SyncScreen(d,StoreId(it))}};composable("conflicts"){activeStore?.let{ConflictsScreen(d,StoreId(it))}};composable("settings"){activeStore?.let{SettingsScreen(d,StoreId(it),nav)}}}}

@Composable private fun ConnectionScreen(d:V1PresentationDependencies,onConnected:(String)->Unit){val vm:ConnectionViewModel=viewModel(factory=vmFactory{ConnectionViewModel(d)});val state by vm.state.collectAsState();var url by rememberSaveable{mutableStateOf("")};var key by rememberSaveable{mutableStateOf("")};var secret by rememberSaveable{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("اتصال فروشگاه",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(url,{url=it},label={Text("Store URL")},modifier=Modifier.fillMaxWidth());OutlinedTextField(key,{key=it},label={Text("Consumer Key")},modifier=Modifier.fillMaxWidth());OutlinedTextField(secret,{secret=it},label={Text("Consumer Secret")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());if(state is FeatureUiState.Error)Text((state as FeatureUiState.Error).message);Button(enabled=url.isNotBlank()&&key.isNotBlank()&&secret.isNotBlank(),onClick={vm.connect(url,key,secret)},modifier=Modifier.fillMaxWidth()){Text("اتصال")}}}
@Composable private fun Dashboard(nav:NavHostController,s:StoreId){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("Dashboard",style=MaterialTheme.typography.headlineLarge);Text("Store: ${s.value}");Button({nav.navigate("orders")},Modifier.fillMaxWidth()){Text("سفارش‌ها")};Button({nav.navigate("products")},Modifier.fillMaxWidth()){Text("محصولات")};Button({nav.navigate("attributes")},Modifier.fillMaxWidth()){Text("ویژگی‌ها")};Button({nav.navigate("sync")},Modifier.fillMaxWidth()){Text("همگام‌سازی")};Button({nav.navigate("conflicts")},Modifier.fillMaxWidth()){Text("تعارض‌ها")};OutlinedButton({nav.navigate("settings")},Modifier.fillMaxWidth()){Text("تنظیمات")}}}
@Composable private fun OrdersScreen(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm:OrdersViewModel=viewModel(factory=vmFactory{OrdersViewModel(d)});val state by vm.state.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.load(s,1,q.ifBlank{null})};Column(Modifier.fillMaxSize().padding(16.dp)){OutlinedTextField(q,{q=it},label={Text("جستجوی سفارش")},modifier=Modifier.fillMaxWidth());when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("سفارشی وجود ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){o->ListItem(headlineContent={Text("#${o.number}")},supportingContent={Text("${o.status} • ${o.total.orEmpty()} ${o.currency.orEmpty()}")},modifier=Modifier.clickable{nav.navigate("orders/${o.id.value}")})}}}}}
@Composable private fun OrderDetailScreen(d:V1PresentationDependencies,s:StoreId,id:EntityId){val vm:OrderDetailViewModel=viewModel(factory=vmFactory{OrderDetailViewModel(d)});val state by vm.state.collectAsState();var note by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,id){vm.load(s,id)};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->{};is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->{Text("Order #${x.value.number}",style=MaterialTheme.typography.headlineSmall);Text("Status: ${x.value.status}");Text("Total: ${x.value.total.orEmpty()} ${x.value.currency.orEmpty()}");Text("Payment: ${x.value.payment?.methodTitle.orEmpty()}");Text("Items: ${x.value.items.size}");OutlinedTextField(note,{note=it},label={Text("یادداشت")},modifier=Modifier.fillMaxWidth());Button(enabled=note.isNotBlank(),onClick={vm.note(s,id,note);note=""}){Text("افزودن یادداشت")};Button(onClick={vm.update(s,x.value.copy(status=OrderStatus.PROCESSING))}){Text("در حال پردازش")}}}}}
@Composable private fun ProductsScreen(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm:ProductsViewModel=viewModel(factory=vmFactory{ProductsViewModel(d)});val state by vm.state.collectAsState();var q by rememberSaveable{mutableStateOf("")};LaunchedEffect(s,q){vm.load(s,1,q.ifBlank{null})};Column(Modifier.fillMaxSize().padding(16.dp)){OutlinedTextField(q,{q=it},label={Text("جستجوی محصول")},modifier=Modifier.fillMaxWidth());when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("محصولی وجود ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){p->ListItem(headlineContent={Text(p.name)},supportingContent={Text("${p.type} • SKU ${p.sku.orEmpty()}")},modifier=Modifier.clickable{nav.navigate("products/${p.id.value}")})}}}}}
@Composable private fun ProductDetailScreen(d:V1PresentationDependencies,s:StoreId,id:EntityId,nav:NavHostController){val vm:ProductDetailViewModel=viewModel(factory=vmFactory{ProductDetailViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s,id){vm.load(s,id)};Column(Modifier.fillMaxSize().padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->{};is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->{Text(x.value.name,style=MaterialTheme.typography.headlineSmall);Text("Type: ${x.value.type}");Text("SKU: ${x.value.sku.orEmpty()}");Text("Regular: ${x.value.pricing.regular.orEmpty()}");Text("Stock: ${x.value.stock?.quantity?.toString().orEmpty()}");Button({nav.navigate("variations/${x.value.id.value}")}){Text("Variations")};Button(onClick={vm.save(s,x.value.copy(status=ProductStatus.PUBLISHED))}){Text("ذخیره")}}}}}
@Composable private fun VariationsScreen(d:V1PresentationDependencies,s:StoreId,p:EntityId){val vm:VariationsViewModel=viewModel(factory=vmFactory{VariationsViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s,p){vm.load(s,p)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Variations",style=MaterialTheme.typography.headlineSmall);when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("Variation ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){v->ListItem(headlineContent={Text(v.sku.orEmpty())},supportingContent={Text(v.attributes.joinToString(" • "){a->"${a.name}: ${a.option}"})})}}}}}
@Composable private fun AttributesScreen(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){val vm:AttributesViewModel=viewModel(factory=vmFactory{AttributesViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Attributes",style=MaterialTheme.typography.headlineSmall);when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("ویژگی ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){a->ListItem(headlineContent={Text(a.name)},supportingContent={Text(a.slug)},modifier=Modifier.clickable{nav.navigate("terms/${a.id.value}")})}}}}}
@Composable private fun TermsScreen(d:V1PresentationDependencies,s:StoreId,a:EntityId){val vm:TermsViewModel=viewModel(factory=vmFactory{TermsViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s,a){vm.load(s,a)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Terms",style=MaterialTheme.typography.headlineSmall);when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("Term ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){t->ListItem(headlineContent={Text(t.name)},supportingContent={Text(t.slug.orEmpty())})}}}}}
@Composable private fun SyncScreen(d:V1PresentationDependencies,s:StoreId){val vm:SyncViewModel=viewModel(factory=vmFactory{SyncViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Sync",style=MaterialTheme.typography.headlineSmall);when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->{};is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->Text("State: ${x.value.state}")};Button({vm.sync(s)}){Text("Sync now")}}}
@Composable private fun ConflictsScreen(d:V1PresentationDependencies,s:StoreId){val vm:ConflictsViewModel=viewModel(factory=vmFactory{ConflictsViewModel(d)});val state by vm.state.collectAsState();LaunchedEffect(s){vm.load(s)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Conflicts",style=MaterialTheme.typography.headlineSmall);when(val x=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("تعارضی وجود ندارد");is FeatureUiState.Error->Text(x.message);is FeatureUiState.Success->LazyColumn{items(x.value){c->Card(Modifier.fillMaxWidth().padding(vertical=4.dp)){Column(Modifier.padding(12.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text("${c.entityType} / ${c.entityId.value}");Text("Local: ${c.localSnapshot}");Text("Server: ${c.serverSnapshot}");Row{Button({vm.resolve(s,c.id,ConflictResolution.KEEP_LOCAL)}){Text("Keep Local")};Spacer(Modifier.width(8.dp));OutlinedButton({vm.resolve(s,c.id,ConflictResolution.KEEP_SERVER)}){Text("Keep Server")}}}}}}}}}
@Composable private fun SettingsScreen(d:V1PresentationDependencies,s:StoreId,nav:NavHostController){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Settings",style=MaterialTheme.typography.headlineSmall);Button({d.onStoreDisconnected();nav.navigate("connection"){popUpTo("settings"){inclusive=true}}}){Text("قطع اتصال")};Button({nav.navigate("sync")}){Text("مدیریت Sync")}}}
