package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.core.domain.usecase.*
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class V1PresentationDependencies(val getStore:GetStore,val connectStore:ConnectStore,val disconnectStore:DisconnectStore,val getOrders:GetOrders,val getOrder:GetOrder,val getProducts:GetProducts,val getProduct:GetProduct,val getConnectionState:GetConnectionState,val getSyncState:GetSyncState)
sealed interface FeatureUiState<out T>{data object Loading:FeatureUiState<Nothing>;data object Empty:FeatureUiState<Nothing>;data class Success<T>(val value:T):FeatureUiState<T>;data class Error(val message:String):FeatureUiState<Nothing>}
class ConnectionViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<StoreConnection>>(FeatureUiState.Loading);val state:StateFlow<FeatureUiState<StoreConnection>>=_state.asStateFlow();fun connect(url:String,key:String,secret:String,onConnected:(StoreId)->Unit){viewModelScope.launch{_state.value=FeatureUiState.Loading;val id=storeIdFor(url);when(val r=deps.connectStore(StoreConnection(id,url.trim().trimEnd('/'),ConnectionState.DISCONNECTED,null),key,secret)){is CoreResult.Success->{_state.value=FeatureUiState.Success(r.value);onConnected(id)};is CoreResult.Failure->_state.value=FeatureUiState.Error(r.error.toString())}}}}
class OrdersViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Order>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(store:StoreId){viewModelScope.launch{_state.value=FeatureUiState.Loading;_state.value=when(val r=deps.getOrders(store,1,50)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class OrderDetailViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<Order>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(store:StoreId,id:EntityId){viewModelScope.launch{_state.value=when(val r=deps.getOrder(store,id)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class ProductsViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<List<Product>>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(store:StoreId){viewModelScope.launch{_state.value=FeatureUiState.Loading;_state.value=when(val r=deps.getProducts(store,1,50)){is CoreResult.Success->if(r.value.isEmpty())FeatureUiState.Empty else FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class ProductDetailViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<Product>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(store:StoreId,id:EntityId){viewModelScope.launch{_state.value=when(val r=deps.getProduct(store,id)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}}}
class SettingsViewModel(private val deps:V1PresentationDependencies):ViewModel(){private val _state=MutableStateFlow<FeatureUiState<ConnectionState>>(FeatureUiState.Loading);val state=_state.asStateFlow();fun load(store:StoreId){viewModelScope.launch{_state.value=when(val r=deps.getConnectionState(store)){is CoreResult.Success->FeatureUiState.Success(r.value);is CoreResult.Failure->FeatureUiState.Error(r.error.toString())}}};fun disconnect(store:StoreId){viewModelScope.launch{when(val r=deps.disconnectStore(store)){is CoreResult.Success->_state.value=FeatureUiState.Success(ConnectionState.DISCONNECTED);is CoreResult.Failure->_state.value=FeatureUiState.Error(r.error.toString())}}}}
private fun <T:ViewModel> factory(create:()->T)=object:ViewModelProvider.Factory{override fun <M:ViewModel>create(modelClass:Class<M>):M=create() as M}
private fun storeIdFor(url:String)=StoreId("store-${url.trim().trimEnd('/').lowercase().hashCode().toUInt().toString(16)}")
@Composable fun V1WooGitApp(deps:V1PresentationDependencies){val nav=rememberNavController();var activeStore by rememberSaveable{mutableStateOf<String?>(null)};NavHost(navController=nav,startDestination="connection"){composable("connection"){V1ConnectionScreen(deps){id->activeStore=id.value;nav.navigate("dashboard"){popUpTo("connection"){inclusive=true}}}};composable("dashboard"){val id=activeStore;if(id!=null)V1Dashboard(nav,id)else Text("Store connection required")};composable("orders"){activeStore?.let{id->V1Orders(deps,StoreId(id),nav)}};composable("orders/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->activeStore?.let{id->V1OrderDetail(deps,StoreId(id),b.arguments?.getString("id")?:"0")}};composable("products"){activeStore?.let{id->V1Products(deps,StoreId(id),nav)}};composable("products/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->activeStore?.let{id->V1ProductDetail(deps,StoreId(id),b.arguments?.getString("id")?:"0")}};composable("settings"){activeStore?.let{id->V1Settings(deps,StoreId(id),nav)}}}}
@Composable private fun V1ConnectionScreen(deps:V1PresentationDependencies,onConnected:(StoreId)->Unit){val vm:ConnectionViewModel=viewModel(factory=factory{ConnectionViewModel(deps)});val state by vm.state.collectAsState();var url by rememberSaveable{mutableStateOf("")};var key by rememberSaveable{mutableStateOf("")};var secret by rememberSaveable{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("اتصال WooCommerce",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(url,{url=it},label={Text("Store URL")},modifier=Modifier.fillMaxWidth());OutlinedTextField(key,{key=it},label={Text("Consumer Key")},modifier=Modifier.fillMaxWidth());OutlinedTextField(secret,{secret=it},label={Text("Consumer Secret")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());when(state){FeatureUiState.Loading->Text("آماده اتصال");is FeatureUiState.Error->Text("خطا: ${state.message}");is FeatureUiState.Success->Text("متصل");else->Unit};Button(enabled=url.isNotBlank()&&key.isNotBlank()&&secret.isNotBlank(),onClick={vm.connect(url,key,secret,onConnected)},modifier=Modifier.fillMaxWidth()){Text("اتصال و ورود")}}}
@Composable private fun V1Dashboard(nav:NavHostController,storeId:String){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Dashboard",style=MaterialTheme.typography.headlineLarge);Text("Store: $storeId");Button({nav.navigate("orders")},Modifier.fillMaxWidth()){Text("سفارش‌ها")};Button({nav.navigate("products")},Modifier.fillMaxWidth()){Text("محصولات")};OutlinedButton({nav.navigate("settings")},Modifier.fillMaxWidth()){Text("تنظیمات")}}}
@Composable private fun V1Orders(deps:V1PresentationDependencies,store:StoreId,nav:NavHostController){val vm:OrdersViewModel=viewModel(factory=factory{OrdersViewModel(deps)});val state by vm.state.collectAsState();LaunchedEffect(store){vm.load(store)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Orders",style=MaterialTheme.typography.headlineSmall);when(val s=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("Empty");is FeatureUiState.Error->Text("Error: ${s.message}");is FeatureUiState.Success->LazyColumn{items(s.value){o->ListItem(headlineContent={Text("#${o.number}")},supportingContent={Text("${o.status} • ${o.total.orEmpty()} ${o.currency.orEmpty()}")},modifier=Modifier.fillMaxWidth().clickable{nav.navigate("orders/${o.id.value}")},overlineContent={Text("${o.items.size} items")})}}}}}
@Composable private fun V1OrderDetail(deps:V1PresentationDependencies,store:StoreId,id:String){val vm:OrderDetailViewModel=viewModel(factory=factory{OrderDetailViewModel(deps)});val state by vm.state.collectAsState();LaunchedEffect(store,id){vm.load(store,EntityId(id))};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Order #$id",style=MaterialTheme.typography.headlineSmall);when(val s=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->{};is FeatureUiState.Error->Text("Error: ${s.message}");is FeatureUiState.Success->Column{Text("Status: ${s.value.status}");Text("Total: ${s.value.total.orEmpty()} ${s.value.currency.orEmpty()}");Text("Payment: ${s.value.payment?.methodTitle.orEmpty()}");Text("Items: ${s.value.items.size}")}}}}
@Composable private fun V1Products(deps:V1PresentationDependencies,store:StoreId,nav:NavHostController){val vm:ProductsViewModel=viewModel(factory=factory{ProductsViewModel(deps)});val state by vm.state.collectAsState();LaunchedEffect(store){vm.load(store)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Products",style=MaterialTheme.typography.headlineSmall);when(val s=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->Text("Empty");is FeatureUiState.Error->Text("Error: ${s.message}");is FeatureUiState.Success->LazyColumn{items(s.value){p->ListItem(headlineContent={Text(p.name)},supportingContent={Text("${p.type} • ${p.pricing.regular.orEmpty()}")},modifier=Modifier.fillMaxWidth().clickable{nav.navigate("products/${p.id.value}")})}}}}}
@Composable private fun V1ProductDetail(deps:V1PresentationDependencies,store:StoreId,id:String){val vm:ProductDetailViewModel=viewModel(factory=factory{ProductDetailViewModel(deps)});val state by vm.state.collectAsState();LaunchedEffect(store,id){vm.load(store,EntityId(id))};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Product #$id",style=MaterialTheme.typography.headlineSmall);when(val s=state){FeatureUiState.Loading->CircularProgressIndicator();FeatureUiState.Empty->{};is FeatureUiState.Error->Text("Error: ${s.message}");is FeatureUiState.Success->Column{Text(s.value.name);Text("Type: ${s.value.type}");Text("SKU: ${s.value.sku.orEmpty()}");Text("Regular: ${s.value.pricing.regular.orEmpty()}");Text("Stock: ${s.value.stock?.quantity?.toString().orEmpty()}")}}}}
@Composable private fun V1Settings(deps:V1PresentationDependencies,store:StoreId,nav:NavHostController){val vm:SettingsViewModel=viewModel(factory=factory{SettingsViewModel(deps)});val state by vm.state.collectAsState();LaunchedEffect(store){vm.load(store)};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Settings",style=MaterialTheme.typography.headlineSmall);when(val s=state){FeatureUiState.Loading->CircularProgressIndicator();is FeatureUiState.Error->Text("Error: ${s.message}");is FeatureUiState.Success->Text("${s.value}");else->Unit};Button(onClick={vm.disconnect(store);nav.navigate("connection"){popUpTo("dashboard"){inclusive=true}}}){Text("Disconnect")}}}
