package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.unit.dp
import androidx.navigation.NavType
import androidx.navigation.compose.*
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.core.domain.usecase.*
import kotlinx.coroutines.launch

class V1PresentationDependencies(val getStore:GetStore,val connectStore:ConnectStore,val disconnectStore:DisconnectStore,val getOrders:GetOrders,val getOrder:GetOrder,val getProducts:GetProducts,val getProduct:GetProduct,val getConnectionState:GetConnectionState,val getSyncState:GetSyncState)

private fun storeIdFor(url:String)=StoreId("store-${url.trim().trimEnd('/').lowercase().hashCode().toUInt().toString(16)}")

@Composable fun V1WooGitApp(deps:V1PresentationDependencies){val nav=rememberNavController();var activeStore by remember{mutableStateOf<StoreId?>(null)};NavHost(navController=nav,startDestination="connection"){composable("connection"){V1ConnectionScreen(deps){id->activeStore=id;nav.navigate("dashboard")}};composable("dashboard"){val id=activeStore;if(id!=null)V1Dashboard(nav,id.value)else LaunchedEffect(Unit){nav.navigate("connection")}};composable("orders"){val id=activeStore;if(id!=null)V1Orders(deps,id,nav)};composable("orders/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->val store=activeStore;if(store!=null)V1OrderDetail(deps,store,b.arguments?.getString("id")?:"0")};composable("products"){val id=activeStore;if(id!=null)V1Products(deps,id,nav)};composable("products/{id}",arguments=listOf(navArgument("id"){type=NavType.StringType})){b->val store=activeStore;if(store!=null)V1ProductDetail(deps,store,b.arguments?.getString("id")?:"0")};composable("settings"){val id=activeStore;if(id!=null)V1Settings(deps,id)}}}

@Composable private fun V1ConnectionScreen(deps:V1PresentationDependencies,onConnected:(StoreId)->Unit){var url by remember{mutableStateOf("")};var key by remember{mutableStateOf("")};var secret by remember{mutableStateOf("")};var status by remember{mutableStateOf("وضعیت: قطع")};var busy by remember{mutableStateOf(false)};val scope=rememberCoroutineScope();Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("اتصال WooCommerce",style=MaterialTheme.typography.headlineMedium);OutlinedTextField(url,{url=it},label={Text("Store URL")},modifier=Modifier.fillMaxWidth());OutlinedTextField(key,{key=it},label={Text("Consumer Key")},modifier=Modifier.fillMaxWidth());OutlinedTextField(secret,{secret=it},label={Text("Consumer Secret")},visualTransformation=PasswordVisualTransformation(),modifier=Modifier.fillMaxWidth());Text(status);Button(enabled=!busy&&url.isNotBlank()&&key.isNotBlank()&&secret.isNotBlank(),onClick={scope.launch{busy=true;val id=storeIdFor(url);val r=deps.connectStore(StoreConnection(id,url.trim().trimEnd('/'),ConnectionState.DISCONNECTED,null),key,secret);busy=false;status=when(r){is CoreResult.Success->{onConnected(id);"متصل"};is CoreResult.Failure->"خطا: ${r.error}"}}},modifier=Modifier.fillMaxWidth()){Text(if(busy)"در حال اتصال…" else "اتصال و ورود")}}}
@Composable private fun V1Dashboard(nav:NavHostController,storeId:String){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Dashboard",style=MaterialTheme.typography.headlineLarge);Text("Store: $storeId");Button({nav.navigate("orders")},Modifier.fillMaxWidth()){Text("سفارش‌ها")};Button({nav.navigate("products")},Modifier.fillMaxWidth()){Text("محصولات")};OutlinedButton({nav.navigate("settings")},Modifier.fillMaxWidth()){Text("تنظیمات")}}}
@Composable private fun V1Orders(deps:V1PresentationDependencies,store:StoreId,nav:NavHostController){var state by remember{mutableStateOf<Any?>(null)};LaunchedEffect(store){state=when(val r=deps.getOrders(store,1,50)){is CoreResult.Success->r.value;is CoreResult.Failure->r.error}};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Orders",style=MaterialTheme.typography.headlineSmall);when(val s=state){null->CircularProgressIndicator();is List<*>->if(s.isEmpty())Text("Empty")else LazyColumn{items(s.filterIsInstance<Order>()){o->ListItem(headlineContent={Text("#${o.id.value}")},supportingContent={Text(o.status.name)},modifier=Modifier.fillMaxWidth())}};else->Text("Error: $s")}}}
@Composable private fun V1OrderDetail(deps:V1PresentationDependencies,store:StoreId,id:String){var state by remember{mutableStateOf<Any?>(null)};LaunchedEffect(id){state=when(val r=deps.getOrder(store,com.samanramezani1377.woogit.core.domain.entity.EntityId(id))){is CoreResult.Success->r.value;is CoreResult.Failure->r.error}};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Order #$id",style=MaterialTheme.typography.headlineSmall);when(val s=state){null->CircularProgressIndicator();is Order->Column{Text("Status: ${s.status}");Text("Items: ${s.items.size}");Text("Payment: ${s.payment?.methodTitle.orEmpty()}")};else->Text("Error: $s")}}}
@Composable private fun V1Products(deps:V1PresentationDependencies,store:StoreId,nav:NavHostController){var state by remember{mutableStateOf<Any?>(null)};LaunchedEffect(store){state=when(val r=deps.getProducts(store,1,50)){is CoreResult.Success->r.value;is CoreResult.Failure->r.error}};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Products",style=MaterialTheme.typography.headlineSmall);when(val s=state){null->CircularProgressIndicator();is List<*>->if(s.isEmpty())Text("Empty")else LazyColumn{items(s.filterIsInstance<Product>()){p->ListItem(headlineContent={Text(p.name)},supportingContent={Text(p.type.name)},modifier=Modifier.fillMaxWidth())}};else->Text("Error: $s")}}}
@Composable private fun V1ProductDetail(deps:V1PresentationDependencies,store:StoreId,id:String){var state by remember{mutableStateOf<Any?>(null)};LaunchedEffect(id){state=when(val r=deps.getProduct(store,com.samanramezani1377.woogit.core.domain.entity.EntityId(id))){is CoreResult.Success->r.value;is CoreResult.Failure->r.error}};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Product #$id",style=MaterialTheme.typography.headlineSmall);when(val s=state){null->CircularProgressIndicator();is Product->Column{Text(s.name);Text("Type: ${s.type}");Text("SKU: ${s.sku.orEmpty()}");Text("Regular: ${s.pricing.regular.orEmpty()}")};else->Text("Error: $s")}}}
@Composable private fun V1Settings(deps:V1PresentationDependencies,store:StoreId){val scope=rememberCoroutineScope();var state by remember{mutableStateOf("Connected")};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("Settings",style=MaterialTheme.typography.headlineSmall);Text("$state • ${store.value}");Button(onClick={scope.launch{deps.disconnectStore(store);state="Disconnected"}}){Text("Disconnect")}}}
