package com.samanramezani1377.woogit.presentation

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import com.samanramezani1377.woogit.core.domain.entity.EntityId
import com.samanramezani1377.woogit.core.domain.entity.StoreId
import com.samanramezani1377.woogit.core.domain.error.CoreResult
import com.samanramezani1377.woogit.core.domain.model.*
import com.samanramezani1377.woogit.core.domain.usecase.*

class WooGitPresentationDependencies(val getStore:GetStore,val getOrders:GetOrders,val getOrder:GetOrder,val getProducts:GetProducts,val getProduct:GetProduct,val getConnectionState:GetConnectionState,val getSyncState:GetSyncState)

private sealed interface LoadState<out T>{data object Loading:LoadState<Nothing>;data object Empty:LoadState<Nothing>;data class Success<T>(val value:T):LoadState<T>;data class Error(val message:String):LoadState<Nothing>}

class OrdersViewModel(private val useCase:GetOrders):ViewModel(){var state by mutableStateOf<LoadState<List<Order>>>(LoadState.Loading);private set;fun load(storeId:String){state=LoadState.Loading;androidx.lifecycle.viewModelScope.launch{state=when(val r=useCase(StoreId(storeId))){is CoreResult.Success->if(r.value.isEmpty())LoadState.Empty else LoadState.Success(r.value);is CoreResult.Failure->LoadState.Error(r.error.toString())}}}}
class ProductsViewModel(private val useCase:GetProducts):ViewModel(){var state by mutableStateOf<LoadState<List<Product>>>(LoadState.Loading);private set;fun load(storeId:String){androidx.lifecycle.viewModelScope.launch{state=when(val r=useCase(StoreId(storeId))){is CoreResult.Success->if(r.value.isEmpty())LoadState.Empty else LoadState.Success(r.value);is CoreResult.Failure->LoadState.Error(r.error.toString())}}}}
class OrderDetailViewModel(private val useCase:GetOrder):ViewModel(){var state by mutableStateOf<LoadState<Order>>(LoadState.Loading);private set;fun load(storeId:String,id:String){androidx.lifecycle.viewModelScope.launch{state=when(val r=useCase(StoreId(storeId),EntityId(id))){is CoreResult.Success->LoadState.Success(r.value);is CoreResult.Failure->LoadState.Error(r.error.toString())}}}}

@Composable fun WooGitApp(deps:WooGitPresentationDependencies){val nav=rememberNavController();NavHost(navController=nav,startDestination="connection"){composable("connection"){ConnectionScreen(deps){nav.navigate("dashboard")}};composable("dashboard"){DashboardScreen{nav.navigate("orders")}{nav.navigate("products")}{nav.navigate("settings")}};composable("orders"){OrdersScreen(deps){id->nav.navigate("orders/store/$id")}};composable("orders/store/{orderId}",arguments=listOf(navArgument("orderId"){type=NavType.StringType})){b->OrderDetailScreen(deps,b.arguments?.getString("orderId")?:"0")};composable("products"){ProductsScreen(deps){id->nav.navigate("products/store/$id")}};composable("products/store/{productId}",arguments=listOf(navArgument("productId"){type=NavType.StringType})){b->ProductDetailScreen(deps,b.arguments?.getString("productId")?:"0")};composable("settings"){SettingsScreen()}}}

@Composable private fun ConnectionScreen(deps:WooGitPresentationDependencies,onConnected:()->Unit){var storeId by remember{mutableStateOf("store-1")};var status by remember{mutableStateOf("در حال بررسی اتصال…")};LaunchedEffect(Unit){val r=deps.getStore(StoreId(storeId));status=when(r){is CoreResult.Success->r.value.state.name;is CoreResult.Failure->"DISCONNECTED"}};Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){Text("اتصال فروشگاه",style=MaterialTheme.typography.headlineMedium);Text("وضعیت: $status");Button(onClick=onConnected){Text("ورود به داشبورد")}}}
@Composable private fun DashboardScreen(onOrders:()->Unit,onProducts:()->Unit,onSettings:()->Unit){Column(Modifier.fillMaxSize().padding(24.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Text("WooGit",style=MaterialTheme.typography.headlineLarge);Text("مدیریت فروشگاه WooCommerce");Button(onClick=onOrders,Modifier.fillMaxWidth()){Text("سفارش‌ها")};Button(onClick=onProducts,Modifier.fillMaxWidth()){Text("محصولات")};OutlinedButton(onClick=onSettings,Modifier.fillMaxWidth()){Text("تنظیمات")}}}
@Composable private fun OrdersScreen(deps:WooGitPresentationDependencies,onOpen:(String)->Unit){val vm:OrdersViewModel=viewModel(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <T:ViewModel>create(modelClass:Class<T>):T=OrdersViewModel(deps.getOrders) as T});LaunchedEffect(Unit){vm.load("store-1")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("سفارش‌ها",style=MaterialTheme.typography.headlineSmall);when(val s=vm.state){LoadState.Loading->CircularProgressIndicator();LoadState.Empty->Text("سفارشی وجود ندارد");is LoadState.Error->Text("خطا: ${s.message}");is LoadState.Success->LazyColumn{items(s.value){order->ListItem(headlineContent={Text("سفارش ${order.id.value}")},supportingContent={Text(order.status.name)},modifier=Modifier.fillMaxWidth())}}}}}
@Composable private fun OrderDetailScreen(deps:WooGitPresentationDependencies,id:String){val vm:OrderDetailViewModel=viewModel(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <T:ViewModel>create(modelClass:Class<T>):T=OrderDetailViewModel(deps.getOrder) as T});LaunchedEffect(id){vm.load("store-1",id)};Column(Modifier.fillMaxSize().padding(16.dp)){Text("جزئیات سفارش",style=MaterialTheme.typography.headlineSmall);when(val s=vm.state){LoadState.Loading->CircularProgressIndicator();LoadState.Empty->{};is LoadState.Error->Text("خطا: ${s.message}");is LoadState.Success->Column{Text("شناسه: ${s.value.id.value}");Text("وضعیت: ${s.value.status}");Text("اقلام: ${s.value.items.size}")}}}}
@Composable private fun ProductsScreen(deps:WooGitPresentationDependencies,onOpen:(String)->Unit){val vm:ProductsViewModel=viewModel(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <T:ViewModel>create(modelClass:Class<T>):T=ProductsViewModel(deps.getProducts) as T});LaunchedEffect(Unit){vm.load("store-1")};Column(Modifier.fillMaxSize().padding(16.dp)){Text("محصولات",style=MaterialTheme.typography.headlineSmall);when(val s=vm.state){LoadState.Loading->CircularProgressIndicator();LoadState.Empty->Text("محصولی وجود ندارد");is LoadState.Error->Text("خطا: ${s.message}");is LoadState.Success->LazyColumn{items(s.value){product->ListItem(headlineContent={Text(product.name)},supportingContent={Text(product.type.name)},modifier=Modifier.fillMaxWidth())}}}}}
@Composable private fun ProductDetailScreen(deps:WooGitPresentationDependencies,id:String){var state by remember{mutableStateOf<LoadState<Product>>(LoadState.Loading)};LaunchedEffect(id){state=when(val r=deps.getProduct(StoreId("store-1"),EntityId(id))){is CoreResult.Success->LoadState.Success(r.value);is CoreResult.Failure->LoadState.Error(r.error.toString())}};Column(Modifier.fillMaxSize().padding(16.dp)){Text("جزئیات محصول",style=MaterialTheme.typography.headlineSmall);when(val s=state){LoadState.Loading->CircularProgressIndicator();LoadState.Empty->{};is LoadState.Error->Text(s.message);is LoadState.Success->Text(s.value.name)}}}
@Composable private fun SettingsScreen(){Column(Modifier.fillMaxSize().padding(24.dp)){Text("تنظیمات",style=MaterialTheme.typography.headlineSmall);Text("اتصال، همگام‌سازی و اعلان‌ها از لایه Application مدیریت می‌شوند.")}}
